### ISSUE TITLE
Not able to install package. Have shifted to ubuntu system and installed a fresh ST3.

### ISSUE THREAD

**Issue by pakhandi** [wbond/package_control#1004]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "package_control.bootstrap in /home/asim/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 109, in bootstrap_dependency
  File "package_control.download_manager in /home/asim/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /home/asim/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 224, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: <unprintable DownloaderException object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "package_control.bootstrap in /home/asim/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 119, in bootstrap_dependency
  File "package_control.console_write in /home/asim/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 34, in console_write
TypeError: __str__ returned non-string (type NoneType)
```

**Comment by pakhandi** [comment]
Resolved it.
It seemed that somehow it was taking up proxy connection while I was on a direct connection.
The system proxy was already removed. Removed proxy from browsers, rebooted the system and it got fixed.
awesome work there :) .
