### ISSUE TITLE
Failing to install new packages

### ISSUE THREAD

**Issue by Stephn-R** [wbond/package_control#1007]
I ran a fresh install of Package Control after purging it according to the instructions and this shows from install:

```
Package Control: Settings change detected, clearing cache
error: Package Control

Error executing: /usr/bin/git config --get branch.master.remote



VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
error: Package Control

Error executing: /usr/bin/git config --get branch.master.merge



VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
Exception in thread Thread-50254:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in /Users/Stephen/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 119, in run
  File "package_control.automatic_upgrader in /Users/Stephen/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 253, in upgrade_packages
  File "package_control.package_installer in /Users/Stephen/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 100, in make_package_list
  File "package_control.upgraders.git_upgrader in /Users/Stephen/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 103, in incoming
  File "package_control.upgraders.git_upgrader in /Users/Stephen/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 64, in get_working_copy_info
AttributeError: 'bool' object has no attribute 'replace'
```

And here is my Settings for Sublime:

```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_extra_width": 1,
	"caret_style": "phase",
	"color_scheme": "Packages/User/SublimeLinter/Facebook (SL).tmTheme",
	"enable_tab_scrolling": false,
	"fade_fold_buttons": false,
	"folder_exclude_patterns":
	[
		".sass-cache",
		".git"
	],
	"font-face": "Hack",
	"font_size": 12,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignore_vcs_packages": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"material_theme_accent_lime": true,
	"material_theme_bold_tab": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"scroll_past_end": true,
	"smart_indent": true,
	"theme": "Material-Theme-Darker.sublime-theme",
	"trim_automatic_white_space": true,
	"trim_trailing_white_space_on_save": false
}
```

**Comment by exipolar** [comment]
I had the same thing, It was because I had the original git package installed. In my case the Git repository was never really initialized (not sure if the previous version of Package Control managed git repo's)

Solution in my case
```
cd (Path to Sublime config folder)/Packages/Git/
git config --add branch.master.merge=true
git config --add branch.master.remote=true
```
^-- this will cause it to throw and error but Package Control will be usable
After using Package Control to remove Git and Install SublimeGit, Everything worked normally again

**Comment by Stephn-R** [comment]
I see. So this is an issue with the Sublime Git package?

**Comment by exipolar** [comment]
Not sure
to find out that it was the git package, I had to run
```
find ./(Sublime Config Dir)/Packages | grep '\.git'
```

The only Package that had a .git repository was in fact Packages/Git/

**Comment by bergtholdt** [comment]
I had the same problem with some package that I installed manually via git in the Packages Folder. To find out, which caused the problem I activated the "debug" option in the Package Control settings. You can then find the package causing this error in the console output.

**Comment by Stephn-R** [comment]
I was able to fix this. Looks like you need to enable `ignore_vcs_package` within the user settings for Package Control
