### ISSUE TITLE
Installing Ensime disables all Package Control commands

### ISSUE THREAD

**Issue by DanPallas** [wbond/package_control#1008]
I've tried this a few times and I can reproduce it every time. 

Install Ensime through Package Control. Ensime appears to install successfully. The command palette no longer shows any Package Control commands. Opening the Package Control prompt through the preferences menu brings up the Package Control prompt, but there aren't any commands. 

I'm using SublimeText 3 build 3083 on mac OS X. Package Control was installed by running the below command in the SublimeText console.

```python
import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
```

**Comment by wbond** [comment]
Please [enable the debug log](https://github.com/wbond/package_control/blob/master/contributing.md) and post the contents of your Sublime Text console.

**Comment by DanPallas** [comment]
Here's the console output

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 176, in on_new
    callback.on_new(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 186, in on_new
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 42, in __init__
  File "env in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 24, in for_window
  File "env in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 76, in __init__
  File "env in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 150, in recalc
  File "./posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 320, in on_deactivated
    callback.on_deactivated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 213, in on_deactivated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 210, in on_activated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 148, in create_text_commands
    cmds.append(class_(view))
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 160, in __init__
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 141, in create_window_commands
    cmds.append(class_(window))
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 154, in __init__
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 36, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 320, in on_deactivated
    callback.on_deactivated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 213, in on_deactivated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 210, in on_activated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 148, in create_text_commands
    cmds.append(class_(view))
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 160, in __init__
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
    callback.on_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 204, in on_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 207, in on_selection_modified
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 320, in on_deactivated
    callback.on_deactivated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 213, in on_deactivated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 210, in on_activated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 320, in on_deactivated
    callback.on_deactivated(v)
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 213, in on_deactivated
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 177, in _invoke
  File "ensime in /Users/dan/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 43, in __init__
AttributeError: 'NoneType' object has no attribute 'logger'

**Comment by wbond** [comment]
Looks like Ensime is broken and is messing up the command palette. I don't know how Package Control could do anything about this.

**Comment by DanPallas** [comment]
Thanks for looking at it.
