### ISSUE TITLE
Cant able to install packages

### ISSUE THREAD

**Issue by ramkibabu** [wbond/package_control#1010]
```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/ramkibabu/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/ramkibabu/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/ramkibabu/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0413448
startup time: 0.0653448
first paint time: 0.0683448
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "2_bootstrap in C:\Program Files\Sublime Text 3\Packages\Package Control.sublime-package", line 103, in plugin_loaded
  File "package_control.loader in C:\Program Files\Sublime Text 3\Packages\Package Control.sublime-package", line 193, in add
  File "./zipfile.py", line 919, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Sublime Text 3\\Installed Packages\\0_package_control_loader.sublime-package'
Package Control: Not running package cleanup since bootstrapping is not yet complete
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Wed, 17 Dec 2014 05:30:00 GMT
    expire date: Fri, 30 Oct 2015 05:29:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.1.2
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Tue, 13 Oct 2015 15:10:04 GMT
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Tue, 13 Oct 2015 15:22:46 GMT
  Content-Type: application/json
  Last-Modified: Tue, 13 Oct 2015 15:20:04 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Caching https://packagecontrol.io/channel_v3.json in C:\Users\ramkibabu\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Traceback (most recent call last):
  File "package_control.package_installer in C:\Program Files\Sublime Text 3\Packages\Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in C:\Program Files\Sublime Text 3\Packages\Package Control.sublime-package", line 74, in disable_packages
ImportError: No module named 'package_control'
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
```

**Comment by wbond** [comment]
Can you try deleting these files and installing fresh?

 - C:\Program Files\Sublime Text 3\Installed Packages\0_package_control_loader.sublime-package
 - C:\Program Files\Sublime Text 3\Packages\Package Control.sublime-package

From looking at the file paths, I believe the issue is that you placed the `Package Control.sublime-package` in the wrong folder. It should be in `Installed Packages/` not `Packages/`.

https://packagecontrol.io/installation
