### ISSUE TITLE
Cannot load package control (Sublime 3)

### ISSUE THREAD

**Issue by Doonut** [wbond/package_control#1016]
Hi, when I try to install Package control either using the automatic method, or the manual method
I get this callback error and package control does not show up in the sublime menu.

```
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\kyle\AppData\Roaming\Sublime Text 3\Packages\Package Control\2_bootstrap.py", line 26, in <module>
    from .package_control.bootstrap import bootstrap_dependency, mark_bootstrapped
  File "C:\Users\kyle\AppData\Roaming\Sublime Text 3\Packages\Package Control\package_control\bootstrap.py", line 19, in <module>
    from .clear_directory import clear_directory
  File "C:\Users\kyle\AppData\Roaming\Sublime Text 3\Packages\Package Control\package_control\clear_directory.py", line 7, in <module>
    from .unicode import unicode_from_os
  File "C:\Users\kyle\AppData\Roaming\Sublime Text 3\Packages\Package Control\package_control\unicode.py", line 7, in <module>
    import ctypes
  File "./ctypes/__init__.py", line 7, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\kyle\AppData\Roaming\Sublime Text 3\Packages\Package Control\Package Control.py", line 10, in <module>
    from .package_control import text, sys_path
  File "C:\Users\kyle\AppData\Roaming\Sublime Text 3\Packages\Package Control\package_control\sys_path.py", line 6, in <module>
    from ctypes import windll, create_unicode_buffer
  File "./ctypes/__init__.py", line 7, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by FichteFoll** [comment]
What is your OS?

**Comment by Doonut** [comment]
Windows 10 x64

**Comment by wbond** [comment]
Can you try the latest version of Package Control with ST3 build 3114 or 3122?

**Comment by Doonut** [comment]
I have reinstalled sublime and the latest version of package control and it seemed to fix the issue.
