### ISSUE TITLE
Failure to install "1 missing dependency"

### ISSUE THREAD

**Issue by flipphillips** [wbond/package_control#1019]
## Description

Console shows error on startup when loading/upgrading packages.

## Details
```
...
reloading plugin Xkcd.xkcd
reloading plugin Zip Browser.Zip Browser
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.version
reloading plugin SFTP.SFTP
plugins loaded
Package Control: Installing 1 missing dependency
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 113, in run
  File "package_control.automatic_upgrader in /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 145, in install_missing
  File "package_control.package_manager in /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1317, in install_package
KeyError: 'load_order'
```

## Configuration
ST3 3095
Mac OS X 10.11.1

## Regression
I've previously tried to 'reinstall' PC to no avail. But- maybe I'm not doing a good enough job of getting things cleaned up.

**Comment by sandrodz** [comment]
This is super annoying.

**Comment by FichteFoll** [comment]
Please enable the debug setting in PC's setting.

**Comment by flipphillips** [comment]
There's not much more detail than I already posted, but sure-

```
startup, version: 3095 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/flip/Library/Application Support/Sublime Text 3/Packages
state path: /Users/flip/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Markdown", "Vintage"]
pre session restore time: 0.179461
using gpu buffer for window
startup time: 0.232013
first paint time: 0.276695
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.run_all_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-tabulate
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-oauthlib
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-requests-oauthlib
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin BinaryPlist.BinaryPlist
reloading plugin Evernote.sublime_evernote
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin glslViewer.glslViewer
reloading plugin LaTeXing.LaTeXing
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Sublimerge Pro.Sublimerge
reloading plugin Writing Style.SublimeWritingStyle
reloading plugin Zip Browser.Zip Browser
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.version
reloading plugin SFTP.SFTP
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3095
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/flip/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/flip/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher DHE-RSA-AES128-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: codexns.com, packagecontrol.io, wbond.net, rc.codexns.io, codexns.io, www.codexns.io
    expire date: Nov 27 23:59:59 2016 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Host: packagecontrol.io
  If-Modified-Since: Sat, 31 Oct 2015 04:10:05 GMT
  If-None-Match: "56343f1d-38349"
  Connection: Keep-Alive
  User-Agent: Package Control v3.1.2
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Sat, 31 Oct 2015 04:15:02 GMT
  Content-Type: application/json
  Last-Modified: Sat, 31 Oct 2015 04:10:05 GMT
  Connection: keep-alive
  ETag: "56343f1d-38349"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/flip/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Download Debug
  URL: https://codeload.github.com/euler0/sublime-glsl/zip/master
  Timeout: 30
  Resolved IP: 192.30.252.147
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/flip/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to codeload.github.com on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/flip/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to codeload.github.com:443 with SSL Using TLSv1/SSLv3 with cipher AES128-SHA
  Server SSL certificate:
    subject: CN=*.github.com,O=GitHub, Inc.,L=San Francisco,S=California,C=US
    subject alt name: *.github.com, github.com
    expire date: Apr 12 12:00:00 2017 GMT
  Certificate validated for codeload.github.com
Package Control: Urllib HTTPS Debug Write
  GET /euler0/sublime-glsl/zip/master HTTP/1.1
  Host: codeload.github.com
  User-Agent: Package Control v3.1.2
  Connection: Keep-Alive
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Content-Length: 6461
  Access-Control-Allow-Origin: https://render.githubusercontent.com
  Content-Security-Policy: default-src 'none'
  X-XSS-Protection: 1; mode=block
  X-Frame-Options: deny
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000
  Vary: Authorization,Accept-Encoding
  ETag: "0443b921dfd842f4c366e0dd7027225956da6524"
  Content-Type: application/zip
  Content-Disposition: attachment; filename=sublime-glsl-master.zip
  Date: Sat, 31 Oct 2015 04:15:04 GMT
  X-GitHub-Request-Id: 81152E03:09B0:4502FA6:56344048
Package Control: Urllib HTTPS Debug General
  Closing connection to codeload.github.com on port 443 after 1 request
Package Control: Skipping cache since the response is a zip file
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package=OpenGL+Shading+Language+%28GLSL%29&package_control_version=3.1.2&sublime_platform=osx&operation=upgrade&sublime_version=3095&old_version=2015.09.13.13.53.36&version=2015.09.13.13.53.36
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #2
Package Control: Urllib HTTPS Debug Write
  GET /submit?package=OpenGL+Shading+Language+%28GLSL%29&package_control_version=3.1.2&sublime_platform=osx&operation=upgrade&sublime_version=3095&old_version=2015.09.13.13.53.36&version=2015.09.13.13.53.36 HTTP/1.1
  Host: packagecontrol.io
  User-Agent: Package Control v3.1.2
  Connection: Keep-Alive
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sat, 31 Oct 2015 04:15:04 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.3.3
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 113, in run
  File "package_control.automatic_upgrader in /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 145, in install_missing
  File "package_control.package_manager in /Users/flip/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1317, in install_package
KeyError: 'load_order'

Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests
```

**Comment by wbond** [comment]
The glslViewer package you are trying to install is broken. It is trying to install a package as a dependency. (https://github.com/patriciogonzalezvivo/sublime-glslViewer/blob/master/dependencies.json)

We'll have to add some checks to ensure package developers don't try this.

**Comment by wbond** [comment]
I should note, you'll need to remove `glslViewer` from the `installed_packages` key of `Packages/User/Package Control.sublime-settings`.

**Comment by wbond** [comment]
I added an issue on the package at https://github.com/patriciogonzalezvivo/sublime-glslViewer/issues/1

**Comment by FichteFoll** [comment]
>There's not much more detail

Believe me, we know better about that ;)

**Comment by flipphillips** [comment]
How -dare- I question the oracles.


On Oct 31, 2015, at 7:21 AM, FichteFoll <notifications@github.com<mailto:notifications@github.com>> wrote:


There's not much more detail

Believe me, we know better about that ;)

**Comment by flipphillips** [comment]
Excellent- thanks for that.I suppose I never saw that before since I -had- that syntax module installed from before but forgot to re-install it when I did a wholesale re-setup of PC to cure some other ills.

Installed it, all is back to semi-normal goodness. Nice to see that it isn’t a bug but rather a ‘enhancement initiator’ :)


On Oct 31, 2015, at 1:00 AM, Will Bond <notifications@github.com<mailto:notifications@github.com>> wrote:


The glslViewer package you are trying to install is broken. It is trying to install a package as a dependency. (https://github.com/patriciogonzalezvivo/sublime-glslViewer/blob/master/dependencies.json)

We'll have to add some checks to ensure package developers don't try this.

**Comment by wbond** [comment]
I added code in c08f68a0232535dd8b0edfb30df01c93275b2235 that will properly error if a package developer specifies a package name as a dependency.
