### ISSUE TITLE
1 missing dependency...

### ISSUE THREAD

**Issue by AlekVa** [wbond/package_control#1026]
I have problem with popup window. It shows every time I start Sublime.

log: 

```
DPI scale: 1.25
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Alek/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Alek/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Alek/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: []
pre session restore time: 0.401981
startup time: 0.464981
first paint time: 0.465981
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.50-pytz
reloading plugin InsertDate.insert_date
reloading plugin Minifier.Minify
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin User.import sublime, sublime_plugin, time
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Alek\AppData\Roaming\Sublime Text 3\Packages\User\import sublime, sublime_plugin, time.py", line 4
    def run(self, edit):
      ^
IndentationError: expected an indented block
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: ÷åò., 29 îêò. 2015 01:00:00 GMT
    expire date: ïîí., 28 íîâ. 2016 00:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.1.2
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Mon, 02 Nov 2015 17:40:03 GMT
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Mon, 02 Nov 2015 17:47:11 GMT
  Last-Modified: Mon, 02 Nov 2015 17:40:03 GMT
  Connection: keep-alive
  ETag: "56379ff3-232add"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from C:\Users\Alek\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: Download Debug
  URL: https://codeload.github.com/packagecontrol/pytz/zip/v2015.4.0
  Timeout: 30
  Resolved IP: 192.30.252.145
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, California, San Francisco, "GitHub, Inc.", *.github.com
    issuer: US, DigiCert Inc, www.digicert.com, DigiCert SHA2 High Assurance Server CA
    common name: *.github.com
    issue date: óò., 08 àïð. 2014 02:00:00 GMT
    expire date: ñð., 12 àïð. 2017 14:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /packagecontrol/pytz/zip/v2015.4.0 HTTP/1.1
  User-Agent: Package Control v3.1.2
  Host: codeload.github.com
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Content-Length: 495431
  Access-Control-Allow-Origin: https://render.githubusercontent.com
  Content-Security-Policy: default-src 'none'
  X-XSS-Protection: 1; mode=block
  X-Frame-Options: deny
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000
  Vary: Authorization,Accept-Encoding
  ETag: "a9dc76f16b4446b6c1e52470530ca652ab5b92ee"
  Content-Type: application/zip
  Content-Disposition: attachment; filename=pytz-2015.4.0.zip
  Date: Mon, 02 Nov 2015 17:47:14 GMT
  X-GitHub-Request-Id: 5BC8C0DC:509A:ACE9512:5637A1A1
Package Control: Skipping cache since the response is a zip file
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package=pytz&old_version=2015.4.0&package_control_version=3.1.2&version=2015.4.0&operation=upgrade&sublime_version=3083&sublime_platform=windows
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: WinINet HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #1
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug Write
  GET /submit?package=pytz&old_version=2015.4.0&package_control_version=3.1.2&version=2015.4.0&operation=upgrade&sublime_version=3083&sublime_platform=windows HTTP/1.1
  User-Agent: Package Control v3.1.2
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Mon, 02 Nov 2015 17:47:22 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.3.3
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Installed missing dependency pytz
Package Control: Skipping automatic upgrade, last run at 2015-11-02 18:44:54, next run at 2015-11-02 19:44:54 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests
Package Control: WinINet HTTPS Debug General
  Closing connection to codeload.github.com on port 443 after 1 request
```

**Comment by FichteFoll** [comment]
I assume the window you are referring to contains the following content:

`1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.`

Is that correct?

I cannot find any hints in your debug log. Please post your `User/Package Control.sublime-settings` file as well.

**Comment by AlekVa** [comment]
Yes this is correct. 

package control.sublime-settings:

{
	"bootstrapped": true,
	"debug": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"InsertDate",
		"Minifier",
		"Package Control"
	]

}

**Comment by wbond** [comment]
1. Is there a directory on your system `Packages\pytz\`?
2. Is there a directory on your system `Packages\0_package_control_loader\`?

**Comment by AlekVa** [comment]
There is pytz directory

**Comment by wbond** [comment]
Now that you've reinstalled Package Control, does it continue to prompt this message each time you restart?

Is there a file named `dependency-metadata.json` in the `pytz` folder?

**Comment by AlekVa** [comment]
Yes, it continues to prompt this message and there is file name dependency-metadata.json

**Comment by wbond** [comment]
Can you delete the `pytz` folder and also `Installed Packages/0_package_control_loader.sublime-package` while Sublime Text is closed and then start Sublime Text?

Ideally, it would prompt once more and then not prompt again.

**Comment by AlekVa** [comment]
After this, it showed "2 missing dependencies..." and I closed Sublime. Not, it show again "1 missing dependency..."

**Comment by wbond** [comment]
According to your log, you have at least one broken file in your `Packages/User/` folder. I wonder if resetting your ST install and seeing if that helps would be a possibility. I would back up your `Packages/` folder and try a fresh install of package control and then try installed InsertDate.

Beyond that, I don't think there is much I can help with since I can't reproduce the issue (I tried on WIndows with ST3).

**Comment by AlekVa** [comment]
Ok, thanks. I'll try reinstalling :)

**Comment by wbond** [comment]
Closing in favor of #1116 - that should help users debug dependency issues.
