### ISSUE TITLE
Package Control is not working in linux

### ISSUE THREAD

**Issue by Revod** [wbond/package_control#1084]
Using elementary OS Freya (ubuntu 14.04) and have the same problem when I open ST build 3103 the console give me this and can't install packages just show the Package Control Panel, etc but nothing load when I pressed a option:
```log
Exception in thread Thread-6:
Traceback (most recent call last):
  File "package_control.package_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 371, in list_repositories
  File "package_control.providers.channel_provider in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 196, in get_repositories
  File "package_control.providers.channel_provider in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 224, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: <unprintable DownloaderException object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 119, in run
  File "package_control.automatic_upgrader in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 249, in upgrade_packages
  File "package_control.package_renamer in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 36, in rename_packages
  File "package_control.package_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 453, in list_available_packages
  File "package_control.package_manager in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 413, in list_repositories
  File "package_control.console_write in /home/revod/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 34, in console_write
TypeError: __str__ returned non-string (type NoneType)
```
and my Preferences > Package Settings > Package Control > Settings - User look like:
```sublime-settings
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Alignment",
		"AutoCompleteJS",
		"Autoprefixer",
		"Babel",
		"Backbone.Marionette",
		"Better CoffeeScript",
		"BracketHighlighter",
		"Color Highlighter",
		"CSS Comments",
		"Ember.js Snippets",
		"Emmet",
		"Emmet Css Snippets",
		"ExpressComplete",
		"Ghost Snippets",
		"Git",
		"GitGutter",
		"Grunt",
		"Grunt Snippets",
		"Handlebars",
		"Jade",
		"Jade Snippets",
		"JavaScript & NodeJS Snippets",
		"Javascript Beautify",
		"JavaScript Completions",
		"JavaScript Snippets",
		"LESS",
		"Package Control",
		"PackageResourceViewer",
		"PackageSync",
		"PxToEm",
		"ReactJS",
		"Ruby on Rails snippets",
		"Sass",
		"SASS Build",
		"SASS Snippets",
		"SCSS",
		"SFTP",
		"SideBarEnhancements",
		"SublimeLinter",
		"SublimeLinter-php",
		"SublimeLinter-ruby",
		"Underscorejs snippets",
		"Vue Syntax Highlight"
	]
}
```

**Comment by Revod** [comment]
Problem fixed, was a error with the last update (i think) of st, and the cache files, I cleaned the cache, reinstalled Sublime Text and install Package Control Again and work
