### ISSUE TITLE
Package control loading any repositories.

### ISSUE THREAD

**Issue by iampritishpatil** [wbond/package_control#1094]
When I run Install Package from Ctrl + P I get 

```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/pritish/.config/sublime-text-3/Packages
state path: /home/pritish/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/pritish/.config/sublime-text-3/Installed Packages
ignored_packages: ["All Autocomplete", "Vintage"]
pre session restore time: 0.120898
loading dictionary Packages/Language - English/en_US.dic
startup time: 0.619219
first paint time: 0.667657
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Google Spell Check.google-spell-check
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarGit.SideBarAPI
reloading plugin SideBarGit.SideBarGit
reloading plugin SideBarGit.SideBarGitCommands
reloading plugin WordCount.WordCount
reloading plugin STProjectMaker.configuration
reloading plugin STProjectMaker.filetask
reloading plugin STProjectMaker.projectmaker
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin Terminal.Terminal
plugins loaded
recreating index
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: Skipping automatic upgrade, last run at 2016-03-11 17:38:12, next run at 2016-03-11 18:38:12 or after
Exception in thread Thread-16:
Traceback (most recent call last):
  File "package_control.package_manager in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 371, in list_repositories
  File "package_control.providers.channel_provider in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 196, in get_repositories
  File "package_control.providers.channel_provider in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 224, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: <unprintable DownloaderException object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 46, in run
  File "package_control.package_installer in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 59, in make_package_list
  File "package_control.package_manager in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 453, in list_available_packages
  File "package_control.package_manager in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 413, in list_repositories
  File "package_control.console_write in /home/pritish/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 34, in console_write
TypeError: __str__ returned non-string (type NoneType)
```

**Comment by iampritishpatil** [comment]
FIxed with Package control reinstall.
