### ISSUE TITLE
TypeError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by ymyqwe** [wbond/package_control#1112]
I've installed Sublime text 3 on my MAC.
When i try to install a plugin via package control. I ran into a problem and can not install plugins.
I've reinstalled my package control[http://wbond.net/sublime_packages/package_control/installation](http://wbond.net/sublime_packages/package_control/installation) like this but it still doesn't work.

Here is my debug log:
`Traceback (most recent call last):
  File "package_control.package_installer in /Users/maniauuuuu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in /Users/maniauuuuu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 91, in disable_packages
TypeError: argument of type 'bool' is not iterable`

**Comment by wbond** [comment]
Paste your Preferences > Settings - User file here.
