### ISSUE TITLE
VCS-based packages can be ignored with the "ignore_vcs_packages" setting.

### ISSUE THREAD

**Issue by klonuo** [wbond/package_control#1115]
I'm getting this error as I started working on a package cloned from git.

I added `"ignore_vcs_packages": true` in my ST settings, but it looks like it does not have any effect as I'm still getting this error.

This shows in console:
```pytb
...
error: Package Control

Error executing: "c:/Program Files/Git/bin/git.exe" config --get branch.db_refresh.remote

VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
error: Package Control

Error executing: "c:/Program Files/Git/bin/git.exe" config --get branch.db_refresh.merge

VCS-based packages can be ignored with the "ignore_vcs_packages" setting.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in D:\Programs\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 119, in run
  File "package_control.automatic_upgrader in D:\Programs\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 253, in upgrade_packages
  File "package_control.package_installer in D:\Programs\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 100, in make_package_list
  File "package_control.upgraders.git_upgrader in D:\Programs\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 103, in incoming
  File "package_control.upgraders.git_upgrader in D:\Programs\Sublime Text\Data\Installed Packages\Package Control.sublime-package", line 64, in get_working_copy_info
AttributeError: 'bool' object has no attribute 'replace'
```

I'm using latest dev release 3114.

**Comment by FichteFoll** [comment]
What exactly did you do to "add" the setting? Please post the contents of your "Preferences > Package Settings > Package Control > Settings - User" file.

**Comment by klonuo** [comment]
Ah, sorry... I added the setting in my user settings
