### ISSUE TITLE
ImportError: No module named 'package_control'

### ISSUE THREAD

**Issue by gjcarneiro** [wbond/package_control#1165]
This started happening after upgrading to ST 3124.  Every package-control command, such as install package, eventually gets this traceback.  I tried reinstalling it from scratch, but it doesn't solve anything.

```
Package Control: Fetching list of available packages and dependencies
  Platform: linux-x64
  Sublime Text Version: 3124
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found system CA bundle at /usr/lib/ssl/certs/ca-certificates.crt (274340 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /home/gjc/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,jurisdictionStateOrProvinceName=Massachusetts,jurisdictionCountryName=US
    subject alt name: packagecontrol.io, wbond.net, sublime.wbond.net, badtls.io, codexns.io, www.codexns.io
    expire date: Nov 27 23:59:59 2016 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Connection: Keep-Alive
  If-None-Match: "57e54f2e-41baa"
  User-Agent: Package Control v3.2.1
  Host: packagecontrol.io
  If-Modified-Since: Fri, 23 Sep 2016 15:50:06 GMT
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Fri, 23 Sep 2016 15:56:03 GMT
  Content-Type: application/json
  Last-Modified: Fri, 23 Sep 2016 15:50:06 GMT
  Connection: keep-alive
  ETag: "57e54f2e-41baa"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /home/gjc/.config/sublime-text-3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: Executing /usr/bin/git symbolic-ref -q HEAD [/home/gjc/.config/sublime-text-3/Packages/Ansible]
Package Control: Executing /usr/bin/git config --get branch.master.remote [/home/gjc/.config/sublime-text-3/Packages/Ansible]
Package Control: Executing /usr/bin/git config --get branch.master.merge [/home/gjc/.config/sublime-text-3/Packages/Ansible]
Package Control: Executing /usr/bin/git fetch origin [/home/gjc/.config/sublime-text-3/Packages/Ansible]
Package Control: Executing /usr/bin/git log ..origin/master [/home/gjc/.config/sublime-text-3/Packages/Ansible]
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Traceback (most recent call last):
  File "package_control.package_installer in /home/gjc/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 154, in on_done
  File "package_control.package_disabler in /home/gjc/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 76, in disable_packages
ImportError: No module named 'package_control'
```

**Comment by wbond** [comment]
Can you provide the full contents of your Console? My guess is there was an import error of the package_control_loader.

**Comment by gjcarneiro** [comment]
Yes, good call.  Something 0-loader was in the "ignored packages" list.  I have no idea how it ended up on that list, though!  Anyway, cleaning up the ignores packages fixed the problem for me.  Thanks!

**Comment by KeithTt** [comment]
good job!!! I look for "ignored_packages" for some time, finally I found it here: https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling
