### ISSUE TITLE
Package Controll Install Command not work

### ISSUE THREAD

**Issue by Andrew-liu** [wbond/package_control#1184]
when I use the `Package Controll Install Command`, It is not work for me and I find some errors in sublime console.

My Sublime version is `Sublime Text 3, Build 3126`

The console error is below:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 140, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 115, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 86, in extract_from_system
  File "package_control.deps.oscrypto._osx._security in /Users/andrew_liu/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 50, in handle_sec_error
OSError: The Trust Settings Record was corrupted.
```

**Comment by wbond** [comment]
Please provide a debug log.

Most likely you are stuck on an old version of Package Control. https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling may be of help.

**Comment by Andrew-liu** [comment]
I reinstalled it and solved it yesterday. I think the problem caused by my Mac. thanks.

I will close this issue.
