### ISSUE TITLE
OSError: The specified keychain is not a valid keychain file.

### ISSUE THREAD

**Issue by tinkpeng** [wbond/package_control#1193]
```
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Exception in thread Thread-15:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 140, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 115, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 43, in extract_from_system
  File "package_control.deps.oscrypto._osx._security in /Users/apple/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 50, in handle_sec_error
OSError: The specified keychain is not a valid keychain file.
```

**Comment by wbond** [comment]
What happens if you open your Keychain Access and select System Roots?

**Comment by tinkpeng** [comment]
There are so many certificates. Nothing special but the three expired certificates: 
     1. Buypass Class 2 CA 1, 
     2. Juur-SK 
     3. EBG Elektronik Sertifika Hizmet Sağlayıcısı. 
But I don't know which one is required by sublime.

**Comment by antientropy-io** [comment]
getting the same here, this is a mobile user account on a work computer. running latest sierra.

**Comment by wbond** [comment]
@antientropy-io Can you provide a console log of the error also?

**Comment by wbond** [comment]
Try following the directions at http://stackoverflow.com/a/14833652/230074

**Comment by wbond** [comment]
The other person who had an issue like this resolved the error - here is the account of the process they took: https://www.belle-aurore.com/mike/2016/12/curse-of-the-wretched-keychain/.

**Comment by tinkpeng** [comment]
just delete the expired login certificate  in keychain access.
It worked for me.
