### ISSUE TITLE
Unable to use command "install package" [Win10 x64 Insider build 14986]

### ISSUE THREAD

**Issue by plneappl** [wbond/package_control#1206]
Trying to "Install package" fails, doesn't show a menu. Debug log:
```
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/simon/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/simon/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/simon/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.164625
warning: mnemonic r not found in menu caption SublimeREPL
startup time: 0.190625
first paint time: 0.191625
first paint time: 0.191625
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Git.git_commands
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Text Pastry.text_pastry
reloading plugin Text Pastry.text_pastry_addons
reloading plugin Text Pastry.text_pastry_clipboard
reloading plugin Text Pastry.text_pastry_selection
reloading plugin SublimeHaskell.autobuild
reloading plugin SublimeHaskell.autocomplete
reloading plugin SublimeHaskell.build
reloading plugin SublimeHaskell.cabal
reloading plugin SublimeHaskell.check_lint
reloading plugin SublimeHaskell.commands
reloading plugin SublimeHaskell.fix_syntax
reloading plugin SublimeHaskell.hdevtools
reloading plugin SublimeHaskell.hsdev
reloading plugin SublimeHaskell.info_popup
reloading plugin SublimeHaskell.parseoutput
reloading plugin SublimeHaskell.repl
Sublime Haskell: SublimeREPL is not installed, ghci/repl commands disabled
reloading plugin SublimeHaskell.stylishhaskell
reloading plugin SublimeHaskell.sublime_haskell_common
reloading plugin SublimeHaskell.symbols
reloading plugin SublimeHaskell.types
reloading plugin SublimeHaskell.worker
plugins loaded
Sublime Haskell: hsdev ping: no pong
Sublime Haskell: Starting hsdev server
Sublime Haskell: hsdev server started at port 4567
Sublime Haskell: connecting to hsdev server (0)...Sublime Haskell: connecting to hsdev server (0)...

Sublime Haskell: connected to hsdev server
Sublime Haskell: connected to hsdev server
Package Control: Skipping automatic upgrade, last run at 2016-12-16 09:21:22, next run at 2016-12-16 10:21:22 or after
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Exception in thread Thread-43:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\simon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 338, in download
OSError: exception: access violation reading 0x0000000000007530
```
Seems similar to #1039 .

**Comment by wbond** [comment]
So apparently I was passing some params as values instead of pointers. 890a05ff583264d3332cd288b4f60a7779b625e7 should fix this. The easiest way to try out would be to delete Package Control from your machine and then clone the master branch into `Packages/Package Control/`.

**Comment by plneappl** [comment]
Yup, works now. Thanks!

**Comment by jasnzhuang** [comment]
good ！~ solved！~

**Comment by GameKyuubi** [comment]
I just got this bug after using reinstalling and using ST3 for a few days.

**Comment by GameKyuubi** [comment]
```
Exception in thread Thread-28:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Storage\Utilities\SublimeText3\Data\Installed Packages\Package Control.sublime-package", line 338, in download
OSError: exception: access violation reading 0x0000000000007530
```

**Comment by GameKyuubi** [comment]
Fixed by deleting package and cloning from master into Package Control.  Is this supposed to be fixed already?

**Comment by wbond** [comment]
Version 3.3.0 of Package Control has been released, which should fix this.
