### ISSUE TITLE
Package Control: The Trust Settings Record was corrupted in version 3.2.1 - New Bug?

### ISSUE THREAD

**Issue by jaggerkyne** [wbond/package_control#1209]
Hi there,

I upgraded to macOS and reinstalled a dev version of sublime text 3. After installing fresh version ST3, I used the installation code on: https://packagecontrol.io/

Sublime version: Build 3125
Package Control: version 3.2.1
debug mode: enabled

But still does not work properly;

The oscrypto-ca-bundle.crt under User is empty, what should be in there?

Is this a new bug for the new year?

Below are the log:

```
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3125
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.upgrade_package_command in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 50, in run
  File "package_control.package_renamer in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 36, in rename_packages
  File "package_control.package_manager in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 450, in list_repositories
  File "package_control.providers.channel_provider in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 140, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 115, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 43, in extract_from_system
  File "package_control.deps.oscrypto._osx._security in /Users/Jagger/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 50, in handle_sec_error
OSError: The Trust Settings Record was corrupted.
```

Is this a new Bug?

**Comment by wbond** [comment]
From what I can tell, there must be issues with the OS trust list on your machine. Reading through https://www.belle-aurore.com/mike/2016/12/curse-of-the-wretched-keychain/ may help in resolving the corruption.
