### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1237]
Here is the full log file on debug mode:

1. [Package Control Version: 3.2.1 debug](https://gist.github.com/evandrocoan/0886e31b24ca6f5f5b5b8a8c404075f1)

```
Package Control: Installing 1 upgradesTraceback (most recent call last):
  File "D:\Sublime\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 268, in reset_last_run
    self.save_last_run(self.last_run)
  File "D:\Sublime\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 99, in save_last_run
    write_compat(fobj, int(last_run))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

The lines 268 are:
```python
File: Packages/Package Control/package_control/automatic_upgrader.py
260:         # If Package Control is being upgraded, just do that and restart
261:         for package in package_list:
262:             if package[0] != 'Package Control':
263:                 continue
264: 
265:             def reset_last_run():
266:                 # Re-save the last run time so it runs again after PC has
267:                 # been updated
268:                 self.save_last_run(self.last_run)
269:             sublime.set_timeout(reset_last_run, 1)
270:             package_list = [package]
271:             break
```
Seem `self.last_run` as not initialized properly.

**Comment by wbond** [comment]
This should be fixed by be43c2b
