### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'replace'

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1238]
I am using the dev version on this commit:

1. https://github.com/wbond/package_control/commit/b4cb03d2457bcac29ba3cfc13689098aee103971

I just did a full clean install of everything, and on the end of it all, it keeps doing this error:
```
Exception in thread Thread-26:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "D:\SublimeText\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 117, in run
    self.upgrade_packages()
  File "D:\SublimeText\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 257, in upgrade_packages
    ignore_packages=self.auto_upgrade_ignore
  File "D:\SublimeText\Data\Packages\Package Control\package_control\package_installer.py", line 99, in make_package_list
    incoming = upgrader.incoming()
  File "D:\SublimeText\Data\Packages\Package Control\package_control\upgraders\git_upgrader.py", line 107, in incoming
    info = self.get_working_copy_info()
  File "D:\SublimeText\Data\Packages\Package Control\package_control\upgraders\git_upgrader.py", line 59, in get_working_copy_info
    branch = res.replace('refs/heads/', '')
AttributeError: 'bool' object has no attribute 'replace'
```

Full debug log: 

1. [Package Control: Debug for AttributeError: 'bool' object has no attribute 'replace'](https://gist.github.com/evandrocoan/757da5a3c7083b26c6069dc3f85f5980)

This is my settings file:

1. https://github.com/evandrocoan/SublimeTextStudio/blob/4346adf573308be7eef05d7795372ed39567880e/User/Package%20Control.sublime-settings

**Comment by wbond** [comment]
This should be resolved by 790bcd6
