### ISSUE TITLE
The package 'bz2' is not available

### ISSUE THREAD

**Issue by xibre** [wbond/package_control#1264]
Hello! I've just upgraded package control to v3.3.0 and I keep getting these errors when I start ST (restarting ST doesn't help):
 - The package 'bz2' is not available
 - An error occurred while trying to upgrade bz2. Please restart Sublime Text to finish the upgrade.
 - 1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

The problem vanished when I reverted Package Control.sublime-package to v3.2.1.

Here is the debug log:
```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Xibre/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Xibre/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Xibre/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.11859
startup time: 0.14959
first paint time: 0.15059
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin EditorConfig.EditorConfig
reloading plugin Modific.Modific
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-contrib-htmlhint.linter
SublimeLinter: htmlhint linter loaded 
reloading plugin SublimeLinter-contrib-jslint.linter
SublimeLinter: jslint linter loaded 
reloading plugin SublimeLinter-gjslint.linter
SublimeLinter: gjslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Babel.Babel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "2_bootstrap in C:\Users\Xibre\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 123, in _background_bootstrap
  File "package_control.loader in C:\Users\Xibre\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 207, in add_or_update
  File "package_control.loader in C:\Users\Xibre\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 291, in add
  File "./zipfile.py", line 919, in __init__
PermissionError: [Errno 13] Permission denied: '0_package_control_loader.sublime-package'

Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: packagecontrol.io
    issuer: US, GeoTrust Inc., RapidSSL SHA256 CA
    common name: packagecontrol.io
    issue date: Sun, 27 Nov 2016 06:00:00 GMT
    expire date: Thu, 28 Nov 2019 05:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Mon, 11 Sep 2017 20:00:08 GMT
  If-None-Match: "59b6eb48-4bcb5"
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Mon, 11 Sep 2017 20:06:56 GMT
  Content-Type: application/json
  Last-Modified: Mon, 11 Sep 2017 20:00:06 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  ETag: W/"59b6eb46-2f142b"
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Caching https://packagecontrol.io/channel_v3.json in C:\Users\Xibre\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
error: Package Control

The package 'bz2' is not available
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0
  Timeout: 30
  Resolved IP: 192.30.253.121
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, California, San Francisco, "GitHub, Inc.", *.github.com
    issuer: US, DigiCert Inc, www.digicert.com, DigiCert SHA2 High Assurance Server CA
    common name: *.github.com
    issue date: Wed, 18 Jan 2017 06:00:00 GMT
    expire date: Fri, 17 Apr 2020 18:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /codexns/sublime-bz2/zip/1.0.0 HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: codeload.github.com
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Content-Length: 238774
  Access-Control-Allow-Origin: https://render.githubusercontent.com
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
  Strict-Transport-Security: max-age=31536000
  Vary: Authorization,Accept-Encoding
  X-Content-Type-Options: nosniff
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
  ETag: "4d9521bc2d1bc6b52f67a13305c123192dfd0571"
  Content-Type: application/zip
  Content-Disposition: attachment; filename=sublime-bz2-1.0.0.zip
  X-Geo-Block-List: 
  Date: Mon, 11 Sep 2017 20:06:58 GMT
  X-GitHub-Request-Id: 06FF:7DBE:3E2FFF:5EDD6A:59B6ECE2
Package Control: Skipping cache since the response is a zip file
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?operation=install&package_control_version=3.3.0&version=1.0.0&package=bz2&sublime_platform=windows&sublime_version=3083
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #1
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug Write
  GET /submit?operation=install&package_control_version=3.3.0&version=1.0.0&package=bz2&sublime_platform=windows&sublime_version=3083 HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Mon, 11 Sep 2017 20:06:59 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.3.3
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Installed missing dependency bz2
Package Control: Skipping automatic upgrade, last run at 2017-09-12 01:58:15, next run at 2017-09-12 02:58:15 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests
Package Control: WinINet HTTPS Debug General
  Closing connection to codeload.github.com on port 443 after 1 request
```

**Comment by ZManor** [comment]
I've got the same problem and it remains while reinstalling.

> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> reloading plugin Package Control.Package Control
> reloading Packages/Package Control/Package Control.sublime-settings
> found 4 files for base name Main.sublime-menu
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "X/threading.py", line 639, in _bootstrap_inner
>   File "X/threading.py", line 596, in run
>   File "2_bootstrap in ***\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 123, in _background_bootstrap
>   File "package_control.loader in ***\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 207, in add_or_update
>   File "package_control.loader in ***\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 291, in add
>   File "X/zipfile.py", line 897, in __init__
> PermissionError: [Errno 13] Permission denied: '0_package_control_loader.sublime-package'
> 
> Package Control: Installing 2 missing dependencies
> Package Control: The dependency '0_package_control_loader' is not available
> Package Control: Installed missing dependency bz2
> Package Control: No updated packages
> error: Package Control
> 
> 1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.

**Comment by wbond** [comment]
You are running a REALLY old version of Sublime Text. If you upgrade to beta build 3114 or 3126 you should be good (https://www.sublimetext.com/3).

**Comment by xibre** [comment]
@wbond Thanks. Upgraded to 3126 and the problem is solved.
