### ISSUE TITLE
Error when trying to run "Install Packages"

### ISSUE THREAD

**Issue by CodeGradox** [wbond/package_control#1267]
I have installed ST3 v3143 on macOS Sierra through the .dmg installer and I installed the package manager. I can list installed packages and it shows Package Control v3.3.0, but when I try to run the install Install Package I get the error shown below.

```
Package Control: Exported certificate: Common Name: KISA RootCA 1, Organizational Unit: Korea Certification Authority Central, Organization: KISA, Country: KR
Package Control: Exported certificate: Common Name: SwissSign Gold Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: DigiCert High Assurance EV Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SwissSign Platinum Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: Certum Trusted Network CA 2, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Organizational Unit: Trustis FPS Root CA, Organization: Trustis Limited, Country: GB
Package Control: Exported certificate: Common Name: UTN-USERFirst-Network Applications, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: Certigna, Organization: Dhimyotis, Country: FR
Package Control: Exported certificate: Common Name: E-Tugra Certification Authority, Organizational Unit: E-Tugra Sertifikasyon Merkezi, Organization: E-Tuğra EBG Bilişim Teknolojileri ve Hizmetleri A.Ş., Locality: Ankara, Country: TR
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Organization: Government Root Certification Authority, Country: TW
Package Control: Exported certificate: Common Name: DST Root CA X3, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: VeriSign Class 1 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Chambers of Commerce Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Email Address: pki@sk.ee, Common Name: EE Certification Centre Root CA, Organization: AS Sertifitseerimiskeskus, Country: EE
Package Control: Exported certificate: Common Name: TWCA Global Root CA, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: SwissSign Gold CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Organizational Unit: RSA Security 2048 V3, Organization: RSA Security Inc
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: WellsSecure Public Root Certificate Authority, Organizational Unit: Wells Fargo Bank NA, Organization: Wells Fargo WellsSecure, Country: US
Package Control: Exported certificate: Common Name: AAA Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: DigiCert Global Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: TWCA Root Certification Authority, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority - G3, Organizational Unit: (c) 2008 GeoTrust Inc. - For authorized use only, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: Class 2 Primary CA, Organization: Certplus, Country: FR
Package Control: Exported certificate: Common Name: UTN - DATACorp SGC, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: Staat der Nederlanden EV Root CA, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Organizational Unit: Go Daddy Class 2 Certification Authority; Organization: The Go Daddy Group, Inc.; Country: US
Package Control: Exported certificate: Common Name: Apple Root CA, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: Swisscom Root EV CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Common Policy, Organizational Unit: FBCA, Organization: U.S. Government, Country: us
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R4
Package Control: Exported certificate: Common Name: Cisco Root CA 2048, Organization: Cisco Systems
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA1, Organization: SECOM Trust.net, Country: JP
Package Control: Exported certificate: Common Name: DST ACES CA X6, Organizational Unit: DST ACES, Organization: Digital Signature Trust, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Commercial, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: Network Solutions Certificate Authority, Organization: Network Solutions L.L.C., Country: US
Exception in thread Thread-10:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 694, in list_available_packages
  File "package_control.package_manager in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 554, in _list_available
  File "package_control.package_manager in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 453, in list_repositories
  File "package_control.providers.channel_provider in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1042, in human_friendly
  File "package_control.deps.asn1crypto.x509 in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1071, in _recursive_humanize
  File "package_control.deps.asn1crypto.core in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1100, in native
  File "package_control.deps.asn1crypto.core in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1702, in native
  File "package_control.deps.asn1crypto.core in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1672, in __unicode__
  File "package_control.deps.asn1crypto._teletex_codec in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x23 in position 32: character maps to \<undefined\>
```

**Comment by gamebox** [comment]
Thanks @wbond for the quick response to this!  Getting all the packages I need for my workflow is very important to my evaluation of this build of ST3, so I appreciate it.

**Comment by xvaier** [comment]
Thanks @wbond, I really appreciate the quick response, I am also currently evaluating the switch to ST3 for my team (from atom) and it is so much faster, so I can't wait to have all the packages I need!

**Comment by wbond** [comment]
Relevant issue: https://github.com/wbond/asn1crypto/issues/60

**Comment by xvaier** [comment]
Does the closed issue in asn1crypto (#60) bring a fix for the OSX version too? Sorry if the answer is obvious, crypto is definitely not my field of expertise.

**Comment by alsnkline** [comment]
I'm trying to install a package on to SB2 V2.0.2, build 2221 and am getting the same error as mentioned here. I also can list installed packages and am running Sierra v10.12.6

My other Mac running v10.12.6 and then same version of SB2 is NOT experiencing the problem!

Like @xvaier I'm not sure how to take advantage of the fix implied in https://github.com/wbond/asn1crypto/issues/60 - or do we just need to wait for the fix to be accepted and available? @wbond

**Comment by wbond** [comment]
The issues has been worked around in asn1crypto, but I still need to cut a release of that. Then upgrade the vendored version in Package Control. Once that is done, I will create a prerelease of PC that you may install to see if it fixes the issue for you.

The root cause of the issue is that there exists in your system CA root list a certificate that is using a Teletex string to store information about it, however that string isn't really a true Teletex string, but rather a string encoded using a different encoding. Unfortunately OpenSSL has a long habit of doing that, however almost all modern certificates use a UTF-8 string instead (because the CA browser forum, the organization that dictates how browsers and CAs deal with certificates, requires that new certs use UTF-8) so most users won't ever run into this issue.

My hope is to have the prerelease out within the next 24 hours or so, but it depends on how much free time I have.

**Comment by hhelmich** [comment]
What is the trick to figuring out which certificate is causing the issue or do I just wait for the fix?  Reinstalling Package Control had no effect.

**Comment by mrdeanjackson** [comment]
not sure what the fix is here either tbh, i've been struggling for a while now.

**Comment by wbond** [comment]
Reinstalling Package Control won't help.

You may be able to figure out what the cert is by looking at the last exported cert in your debug log and finding it in the *System Roots* section of the Keychain Access app. It may be that the next one in the list is the cert causing issues.

**Comment by wbond** [comment]
However, looking at the list in the original post, it seems they aren't alphabetical and Keychain Access seems to sort them alphabetically.

**Comment by hhelmich** [comment]
The list in the console is alphabetical.  If I follow manual installation methods like using git the in packages directory, will that break Package Control in the future?


On September 19, 2017 at 4:53:39 PM, Will Bond (notifications@github.com) wrote:

However, looking at the list in the original post, it seems they aren't alphabetical and Keychain Access seems to sort them alphabetically.

**Comment by alsnkline** [comment]
I just checked - I'm seeing 110 lines of `Package Control: Exported certificate:` before the exception (not sorted alphabetically), and my Keychain Access reports 168 items sorted alphabetically. 

Ugg that's 57 candidates.

I have only one expired certificate in my System Roots - `TÜBİTAK UEKAE Kök Sertifika Hizmet Sağlayıcısı - Sürüm 3` it expired 21 Aug 2017 - its on the trusted list of certs https://support.apple.com/en-us/HT205204

Could it be causing my issues - it gave me an error when I tried to delete it <An error occurred while deleting "TÜBİTAK UEKAE Kök Sertifika Hizmet Sağlayıcısı - Sürüm 3 
Unix[Operation not permitted]>

**Comment by wbond** [comment]
An expired cert won't be the issue. It will be a cert that has a name that uses a character that is part of the encoding https://en.wikipedia.org/wiki/ISO/IEC_8859-1 but not part of https://en.wikipedia.org/wiki/ITU_T.61.

OpenSSL puts ISO-8859-1 in a place there only ITU T.61 should be used, and asn1crypto currently parses things according to the spec. The new version of asn1crypto is going to follow OpenSSL since most libraries now acquiesce to the non-standard behavior.

**Comment by wbond** [comment]
@ralph-carlisle Unfortunately not as I have to fit open source work in around the rest of my life. This morning I went to put out a new asn1crypto release, but the root .io name servers were causing issues, so the test suites wouldn't run on the various CI providers. Maybe later tonight or tomorrow morning I'll have some more time.

**Comment by alsnkline** [comment]
@wbond I looked at the two encoding links you sent and also compared the list of certs installed on my two macs - the one that shows the issue and the one that doesn't.

There are a couple of certs with characters that appear to be in one encoding and not the other eg:
`TÜRKTRUST Elektronik Sertifika Hizmet Sağlayıcısı` the Ü (220)
or `NetLock Arany (Class Gold) Főtanúsítvány` the ő maybe (252)

The thing that seems really weird to me is my two computers have the exact same list of 168 current certs. 
Could there be different versions of certs? 
Is there a delete and reinstall procedure we could follow to try and get the correctly encoded version of the certs installed on our machines?

**Comment by mattpr** [comment]
I figured I would take a look for old/misc certs outside the normal Root CA list provided by Apple.

In my case there were a bunch of openvpn.net CA certs under Keychain Access > System.  I am guessing the openvpn client installs these (awesome).  Deleting them caused the issue to go away for me.

**Comment by mgrandi** [comment]
I have confirmed that it is this silly openVPN cert that somehow got installed, but here is how to check: 

(make sure `oscrypto` is installed)
```
import oscrypto.trust_list
import pdb

try:
    def print_cert_subject(cert, reason):
        print(cert.subject.human_friendly)
    oscrypto.trust_list.get_path(cache_length=0, cert_callback=print_cert_subject)
except Exception as e:
    pdb.post_mortem()
```

then when you are in the debugger, type
`input_.tobytes()`

and it should print out the certificate that it failed on

```
(Pdb) input_.tobytes()
b'http://openvpn.net/localca.html #1433234179'
```

**Comment by Spaider** [comment]
@mgrandi thank for the code but on my machine it completed with no errors but still I am not able to use Package Manager :)

**Comment by lexilya** [comment]
I had a similar OpenVPN cert to that of mgrandi, and removing it solved the issue for me as well. Cheers!

**Comment by dsanders11** [comment]
@wbond, it looks like the new version of `asn1crypto` was put out a couple weeks ago, which should have the fix for this issue, right? Would be great if `package_control` could be updated to use it so this issue is resolved, it's probably impacting quite a few people since `openvpn` is fairly common.

**Comment by wbond** [comment]
@dsanders11 I agree. Unfortunately I don't really have much free time ATM. Perhaps someone can send a PR that I can check over?

**Comment by dsanders11** [comment]
@wbond, created #1277, but without build instructions or an automated build on this repo I'm really just stabbing in the dark and can't test that it fixes anything.

Assuming `asn1crypto` 0.23.0 is a drop-in change and nothing needs to be done to take advantage of the relaxed parsing rules, then it should just be a matter of bumping `package_control` to 3.3.1 after that PR and releasing it.

**Comment by mrdeanjackson** [comment]
@mgrandi thanks wasn't clear on how to test but I found an OpenVPN cert, removed it and that did the trick. Happy days!

**Comment by vills** [comment]
#1277 fixed issue with certificates for me

**Comment by ralph-carlisle** [comment]
@mattpr I found something similar on my system - thanks for pointing me to looking there.  I'm able to get package control to work now.  :)

**Comment by jcvtieck** [comment]
@mattpr that solved the problem for me too.
thanks!

**Comment by alsnkline** [comment]
@mgrandi your answer pointed me to the openVPN cert that was causing my issue just like everyone else - thank you so much.

**Comment by bioball** [comment]
I also have this problem, and @mgrandi's script pointed me to an openvpn cert. What does that cert do? Seems destructive to just delete it.

**Comment by vcasadei** [comment]
How the hell do I find this certificate?

I tried the script and it simply doesn't work. It would be helpful to post a full solution

**Comment by mgrandi** [comment]
I don't know where this cert comes from, you can back it up before removing it if you are scared you might need it

And you can remove it by searching for "openvpn.net" and deleting the cert from keychain manager.app, and then trying package control again.

**Comment by wbond** [comment]
Please try following the directions at https://github.com/wbond/package_control/issues/1293#issuecomment-342595937 and leave a comment there if you still have trouble with the new version

**Comment by nakwa** [comment]
@wbond #1293 worked for me - thanks.

**Comment by muellermichel** [comment]
mattpr's issue was also the case for me, removing OpenVPN fixed it.

**Comment by daveperry202** [comment]
Big thank you from me, removing OpenVPN sorted out my issue

**Comment by bmarto** [comment]
Removing the OpenVPN certs also did the trick for me!
Thank you!

**Comment by bsansouci** [comment]
I had this issue as well, and I solved it doing this https://github.com/wbond/package_control/issues/1302#issuecomment-352076439. It's beta software, but at least I can use sublime text again now.

**Comment by scr1ptc0dejunk1e** [comment]
I seem to be having this issue as well. I get the log message:

`ignored packages updated to : ["package I'm trying to install", "Vintage"]`

I've had this issue with ColorPicker and JavaScript Enhancements.

Here is the console log.

```
DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.325685
startup time: 0.450685
first paint time: 0.477685
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-bs4
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin ApplySyntax.ApplySyntax
reloading plugin ApplySyntax.support
reloading plugin Auto Close HTML Tags.auto_close
reloading plugin BracketGuard.BracketGuard
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin C2console.c2console
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin Console Wrap.console_wrap
reloading plugin DocBlockr.jsdocs
reloading plugin DoxyDoxygen.Doxy
------==== DoxyDoxygen plugins loaded ====------
0 sub-modules to reload
reloading plugin Indent To Parenthesis.indent_to_parenthesis
reloading plugin JSON Reindent.sublime_json_reindent
reloading plugin MarkdownLivePreview.devListener
reloading plugin MarkdownLivePreview.escape_amp
reloading plugin MarkdownLivePreview.functions
reloading plugin MarkdownLivePreview.image_manager
reloading plugin MarkdownLivePreview.MarkdownLivePreview
reloading plugin MarkdownLivePreview.MLPApi
reloading plugin MarkdownLivePreview.setting_names
reloading plugin MarkdownPreview.markdown_preview
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin MultiEditUtils.MultiEditUtils
reloading plugin MultiEditUtils.selection_fields
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-annotations.linter
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin ESLint.ESLint
plugins loaded
c2console loaded
[Console Wrap] ****************************** loaded ******************************
reloading settings Packages/User/ApplySyntax.ext-list
reloading settings Packages/User/Bash.sublime-settings
Package Control: Unable to remove old directory JavaScript Completions - deferring until next start
Package Control: Skipping automatic upgrade, last run at 2019-08-01 16:30:28, next run at 2019-08-01 17:30:28 or after
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: packagecontrol.io
    issuer: xxx, xxx, xxx, xxx, xxx, xxx, xxx@xxx.xx.xx
    common name: packagecontrol.io
    issue date: Tue, 29 May 2018 12:00:00 GMT
    expire date: Thu, 28 Nov 2019 01:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  If-None-Match: "5d4271d4-5346a"
  If-Modified-Since: Thu, 01 Aug 2019 05:00:04 GMT
  Accept-Encoding: bzip2,gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Thu, 01 Aug 2019 05:17:36 GMT
  Content-Type: application/json
  Content-Length: 341124
  Last-Modified: Thu, 01 Aug 2019 05:10:04 GMT
  Connection: keep-alive
  ETag: "5d42742c-53484"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Accept-Ranges: bytes
Package Control: Caching https://packagecontrol.io/channel_v3.json in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
ignored packages updated to: ["ColorPicker", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.0
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Download Debug
  URL: https://codeload.github.com/weslly/ColorPicker/zip/1.14.3
  Timeout: 30
  Resolved IP: 192.30.255.120
reloading /C/Users/xxx/AppData/Roaming/Sublime Text 3/Packages/User/Package Control.sublime-settings
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, California, San Francisco, "GitHub, Inc.", *.github.com
    issuer: xx, xxx, xxx, xxx, xxx, xxx, xxx@xxx.xx.xx
    common name: *.github.com
    issue date: Mon, 08 Jul 2019 12:00:00 GMT
    expire date: Fri, 17 Jul 2020 00:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /weslly/ColorPicker/zip/1.14.3 HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: codeload.github.com
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: bzip2,gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 403 Forbidden
  Connection: close
  Content-Type: text/html
  Cache-Control: no-cache
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Content-Security-Policy: frame-ancestors
  Content-Length: 1025
Package Control: Skipping cache since the HTTP status code not one of: 200, 304
Package Control: Error downloading package. HTTP error 403 downloading https://codeload.github.com/weslly/ColorPicker/zip/1.14.3.
error: Package Control

Unable to download ColorPicker. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading /C/Users/xxx/AppData/Roaming/Sublime Text 3/Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: WinINet HTTPS Debug General
  Closing connection to codeload.github.com on port 443 after 1 request
```

**Comment by FichteFoll** [comment]
This is your problem:
```
Package Control: Error downloading package. HTTP error 403 downloading https://codeload.github.com/weslly/ColorPicker/zip/1.14.3.
```

Accessing https://codeload.github.com/weslly/ColorPicker/zip/1.14.3 works in my browser and with curl. Maybe try again now? (link to tag page: https://github.com/weslly/ColorPicker/releases/tag/1.14.3)

**Comment by scr1ptc0dejunk1e** [comment]
Thanks. I'm an idiot. I should have tried the link. My work is blocking the URL to that package for some reason. Thanks for your time and sorry for the trouble.

**Comment by deathaxe** [comment]
Closing as this is no issue with PC 3.4.1 anymore, which ships an updated asn1crypto.
