### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by CheiZhei** [wbond/package_control#1276]
debug message:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 694, in list_available_packages
  File "package_control.package_manager in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 554, in _list_available
  File "package_control.package_manager in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 453, in list_repositories
  File "package_control.providers.channel_provider in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 650, in download
  File "package_control.downloaders.caching_downloader in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 176, in cache_result
  File "package_control.http_cache in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 88, in set
  File "package_control.open_compat in C:\Program Files (x86)\Sublime Text3\Data\Installed Packages\Package Control.sublime-package", line 22, in open_compat
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Sublime Text3\\Data\\Packages\\User\\Package Control.cache\\01524fae79697630d0454ba3fabd9414.info'

**Comment by wbond** [comment]
Use an admin account to delete `C:\Program Files (x86)\Sublime Text3\Data\Packages\User\Package Control.cache`. Those files are all safe to delete.
