### ISSUE TITLE
WinError 10013 - a true nightmare and a damn headache 

### ISSUE THREAD

**Issue by haxulav** [wbond/package_control#1296]
I just tried everything I could now... 

Basically, I had Sublime 3 running just fine with everything I needed including package control, but I can't be sure what was the cause - I installed nodejs, python(they work kind of fine) - but sublime stopped of getting connection access with the above error(WinError 10013).

My firewall settings are fine - tried to disable it completely for testing - no positive results.

My guess it is somehow related to(port, obviously) recently installed Python or nodejs and there's some conflict between them and sublime.

I tried to re-install sublime by uninstalling it with windows(10) default tool and then removing two following folders:
%APPDATA%\Sublime Text 3
and
%LOCALAPPDATA%\Sublime Text 3

Also tried to disable to reset setting in internet explorer as it said in the troubleshooting guide and disable the checkbox of the certificate... Just nothing. Same negative result...

Basically after reinstalling sublime(with machine restart), opening it and trying to copy-pase the Installing code of Control Package from the website I got:

>>> import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
Traceback (most recent call last):
  File "./python3.3/urllib/request.py", line 1248, in do_open
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1274, in http_open
  File "./python3.3/urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>

However when I launch the sublime, I don't see anything: no errors of missing something or anything like that. It ends with the line of:
"plugins loaded"
and that's it.

**Comment by haxulav** [comment]
Anyone... please?

I just tried everything I could think of, except "format c:"

**Comment by FichteFoll** [comment]
You could try a different downloader after you managed to install PC again. For that, either try the built-in method in the tools menu or do it manually (by downloading the package file and placing it in the Installed Packages folder). No idea about your error though.

**Comment by haxulav** [comment]
I can't install it manually too... fuckin' bullshit :/

DPI scale: 2
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/myuser/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.113257
startup time: 0.222257
first paint time: 0.222257
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "2_bootstrap in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\New folder\Package Control.sublime-package", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "package_control.bootstrap in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\New folder\Package Control.sublime-package", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "package_control.loader in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\New folder\Package Control.sublime-package", line 57, in <module>
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "Package Control in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\New folder\Package Control.sublime-package", line 14, in <module>
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
plugins loaded


I uninstalled nodejs, python, visual code studio...
for real... WTF

**Comment by haxulav** [comment]
Alrighty... managed to actually install manually the package control, BUT... when I try to install packages by ctrl+shift+p > install package, I get:

Package Control: Skipping automatic upgrade, last run at 2017-11-17 14:12:06, next run at 2017-11-17 15:12:06 or after
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions downloading https://packagecontrol.io/channel_v3.json.


Now, I'm allowing SUBLIME_TEXT.EXE full access to internet with my firewall, perhaps there's something else I should check(because there no other connection that tries to go out + before it worked just fine)...
WHAT CAN IT BE omfg...

**Comment by haxulav** [comment]
Oh maaaan... this thing drives me crazy. 

I have the same issue with on my second machine I haven't been touched for about 1 months.... EXACTLY THE SAME.
So what the heck can it be?!

BTW: When I tried to install manually the CP to dedicated folder (eg Contrrol Package) I hit this shit:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "2_bootstrap in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control\Package Control.sublime-package", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "package_control.bootstrap in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control\Package Control.sublime-package", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "package_control.loader in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control\Package Control.sublime-package", line 57, in <module>
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "Package Control in C:\Users\myuser\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control\Package Control.sublime-package", line 14, in <module>
  File "./python3.3/ntpath.py", line 111, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
plugins loaded



BUT, when I put the *.package file to Installed Packages without putting it to sub folder, It actually installed, but with the above error of:

Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Error downloading channel. URL error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions downloading https://packagecontrol.io/channel_v3.json.



WHY OH GOD... WHYYYY

**Comment by FichteFoll** [comment]
>when I put the *.package file to Installed Packages without putting it to sub folder, It actually installed

This is the proper procedure. Putting `.sublime-packages` in a subfolder is unexpected and will produced unexpected results, like the ones you were seeing.

You may try using one of the alternative downloaders by adjusting the setting outlined here:
https://github.com/wbond/package_control/blob/6ec927be4a0b22be6e8eb24e7226828fc88611f6/Package%20Control.sublime-settings#L126-L142

It won't solve the root cause (which, again, I have no idea what it is), but it may allow you to work around it and be able to actually use PC.

**Comment by FichteFoll** [comment]
Actually, regarding the WinInet error first check out this troubleshooting guide: https://packagecontrol.io/docs/troubleshooting#Windows_Errors_12029_and_12057

Urllib might be failing for the same reason.
