### ISSUE TITLE
Still having asn1crypto._teletex_codec bug with certificats

### ISSUE THREAD

**Issue by hfreville** [wbond/package_control#1302]
Hello,

I'm having problem using package control to install new packages.
Tried the pre-release in #1293 but keep having exception.
```
  File "package_control.deps.asn1crypto._teletex_codec in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x23 in position 43: character maps to <undefined>
```

Running Sublime Text 3 on OS X El Capitan 10.11.6
Here console logs :

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/huf/Library/Application Support/Sublime Text 3/Packages
state path: /Users/huf/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.37472
startup time: 0.451127
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
environment variables loaded using: /bin/bash -l
Package Control: Exported certificate: Common Name: AddTrust Class 1 CA Root, Organizational Unit: AddTrust TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R3
Package Control: Exported certificate: Common Name: Go Daddy Root Certificate Authority - G2; Organization: GoDaddy.com, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R2
Package Control: Exported certificate: Common Name: VeriSign Class 2 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G3, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: TC TrustCenter Class 2 CA II, Organizational Unit: TC TrustCenter Class 2 CA, Organization: TC TrustCenter GmbH, Country: DE
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Trusted Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: WellsSecure Public Root Certificate Authority, Organizational Unit: Wells Fargo Bank NA, Organization: Wells Fargo WellsSecure, Country: US
Package Control: Exported certificate: Common Name: OISTE WISeKey Global Root GA CA; Organizational Unit: OISTE Foundation Endorsed, Copyright (c) 2005; Organization: WISeKey; Country: CH
Package Control: Exported certificate: Organization: TÜRKTRUST Bilgi İletişim ve Bilişim Güvenliği Hizmetleri A.Ş. (c) Kasım 2005, Locality: Ankara, Country: TR, Common Name: TÜRKTRUST Elektronik Sertifika Hizmet Sağlayıcısı
Package Control: Exported certificate: Organizational Unit: Class 3 Public Primary Certification Authority; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Common Name: UTN-USERFirst-Client Authentication and Email, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: AdminCA-CD-T01; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: CH
Package Control: Exported certificate: Email Address: Info@izenpe.com, Common Name: Izenpe.com, Locality: Avda del Mediterraneo Etorbidea 3 - 01010 Vitoria-Gasteiz, Organization: IZENPE S.A. - CIF A-01337260-RMerc.Vitoria-Gasteiz T1055 F62 S8, Country: ES
Package Control: Exported certificate: Common Name: XRamp Global Certification Authority, Organization: XRamp Security Services Inc, Organizational Unit: www.xrampsecurity.com, Country: US
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 55, in run
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 2003, in record_usage
  File "package_control.download_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1076, in human_friendly
  File "package_control.deps.asn1crypto.x509 in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1105, in _recursive_humanize
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 872, in native
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1773, in native
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1743, in __unicode__
  File "package_control.deps.asn1crypto._teletex_codec in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x23 in position 43: character maps to <undefined>

Package Control: Exported certificate: Common Name: AddTrust Class 1 CA Root, Organizational Unit: AddTrust TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R3
Package Control: Exported certificate: Common Name: Go Daddy Root Certificate Authority - G2; Organization: GoDaddy.com, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R2
Package Control: Exported certificate: Common Name: VeriSign Class 2 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G3, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: TC TrustCenter Class 2 CA II, Organizational Unit: TC TrustCenter Class 2 CA, Organization: TC TrustCenter GmbH, Country: DE
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Trusted Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: WellsSecure Public Root Certificate Authority, Organizational Unit: Wells Fargo Bank NA, Organization: Wells Fargo WellsSecure, Country: US
Package Control: Exported certificate: Common Name: OISTE WISeKey Global Root GA CA; Organizational Unit: OISTE Foundation Endorsed, Copyright (c) 2005; Organization: WISeKey; Country: CH
Package Control: Exported certificate: Organization: TÜRKTRUST Bilgi İletişim ve Bilişim Güvenliği Hizmetleri A.Ş. (c) Kasım 2005, Locality: Ankara, Country: TR, Common Name: TÜRKTRUST Elektronik Sertifika Hizmet Sağlayıcısı
Package Control: Exported certificate: Organizational Unit: Class 3 Public Primary Certification Authority; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Common Name: UTN-USERFirst-Client Authentication and Email, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: AdminCA-CD-T01; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: CH
Package Control: Exported certificate: Email Address: Info@izenpe.com, Common Name: Izenpe.com, Locality: Avda del Mediterraneo Etorbidea 3 - 01010 Vitoria-Gasteiz, Organization: IZENPE S.A. - CIF A-01337260-RMerc.Vitoria-Gasteiz T1055 F62 S8, Country: ES
Package Control: Exported certificate: Common Name: XRamp Global Certification Authority, Organization: XRamp Security Services Inc, Organizational Unit: www.xrampsecurity.com, Country: US
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 694, in list_available_packages
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 554, in _list_available
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 453, in list_repositories
  File "package_control.providers.channel_provider in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1076, in human_friendly
  File "package_control.deps.asn1crypto.x509 in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1105, in _recursive_humanize
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 872, in native
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1773, in native
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1743, in __unicode__
  File "package_control.deps.asn1crypto._teletex_codec in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x23 in position 43: character maps to <undefined>
```

Thank you,

**Comment by wbond** [comment]
Hmm, is that with debugging turned on?

Can you open the Sublime Text console and execute the following?

```python
import package_control; package_control.__version__
```

**Comment by hfreville** [comment]
Hello,

Here the result :
```
>>> 
>>> import package_control; package_control.__version__
'3.3.1-beta1'
```

I enabled debug for package control and retry package install
```
>>> 
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3143
  Package Control Version: 3.3.1-beta1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority; Organizational Unit: (c) 2006 Entrust, Inc., www.entrust.net/CPS is incorporated by reference; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Autoridad de Certificacion Firmaprofesional CIF A62634068, Country: ES
Exception in thread Thread-9:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 694, in list_available_packages
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 554, in _list_available
  File "package_control.package_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 453, in list_repositories
  File "package_control.providers.channel_provider in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 201, in get_repositories
  File "package_control.providers.channel_provider in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 87, in fetch
  File "package_control.download_manager in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 117, in download
  File "package_control.downloaders.urllib_downloader in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 317, in setup_opener
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 31, in get_ca_bundle_path
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 166, in get_system_ca_bundle_path
  File "package_control.deps.oscrypto.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 122, in get_path
  File "package_control.deps.oscrypto._osx.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 153, in extract_from_system
  File "package_control.deps.oscrypto._osx.trust_list in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 177, in _cert_callback
  File "package_control.ca_certs in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 108, in print_cert_subject
  File "package_control.deps.asn1crypto.x509 in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1076, in human_friendly
  File "package_control.deps.asn1crypto.x509 in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1105, in _recursive_humanize
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 872, in native
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1773, in native
  File "package_control.deps.asn1crypto.core in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 1743, in __unicode__
  File "package_control.deps.asn1crypto._teletex_codec in /Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 20, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x23 in position 43: character maps to <undefined>


```

**Comment by wbond** [comment]
Weird. The subject name should be using a class that uses the cp1252 charset, which does have a mapping for char 0x23. Can you try deleting:

 - `/Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package`
 - `/Users/huf/Library/Application Support/Sublime Text 3/Packages/Package Control/` if it exists

And then download https://packagecontrol.io/prerelease/Package%20Control.sublime-package into `/Users/huf/Library/Application Support/Sublime Text 3/Installed Packages/` and restart Sublime Text.

**Comment by hfreville** [comment]
Hello,

After upgrading to last pre-release, it's better
No more exceptions in console and i'm able to install new packages :-)

version used :
```
>>> import package_control; package_control.__version__
'3.3.1-beta4'
```

Thank you,
