### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable while batch calling satisfy_dependencies_command

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1314]
I created a python script to batch clone git repositories and call `satisfy_dependencies` command. The script does this:
```
for package in packages:
    git clone --recursive ...
    run_command("satisfy_dependencies")
```

But after a few calls I start getting:
```
Exception in thread Thread-405:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\commands\satisfy_dependencies_command.py", line 46, in run
  File "C:\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\package_manager.py", line 1551, in install_dependencies
  File "C:\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\package_manager.py", line 678, in list_available_dependencies
  File "C:\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\package_manager.py", line 554, in _list_available
  File "C:\SUBLIM~1\INSTAL~1\PACKAG~1.SUB\package_control\package_manager.py", line 414, in list_repositories
TypeError: 'NoneType' object is not subscriptable
```

Now I put it outside the loop, like:
```
for package in packages:
    git clone --recursive ...

run_command("satisfy_dependencies")
```
And still giving the error after iterating throw all packages.

The code is:
```python
File: package_manager.py
400:     def list_repositories(self):
401:         """
402:         Returns a master list of all repositories pulled from all sources
403: 
404:         These repositories come from the channels specified in the
405:         "channels" setting, plus any repositories listed in the
406:         "repositories" setting.
407: 
408:         :return:
409:             A list of all available repositories
410:         """
411: 
412:         cache_ttl = self.settings.get('cache_length')
413: 
414:         repositories = self.settings.get('repositories')[:]
415:         channels = self.settings.get('channels')
```

**Comment by deathaxe** [comment]
The way Package Control has to be implemented to be compatible with ST2 ends up in various possible race conditions.

That said, I am uncertein whether those functions are meant for external use anyway. They are not part of any API documentation.

The only public API is the `events` module.
