### ISSUE TITLE
Ran 60 tests, FAILED (failures=3, errors=7)

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1317]
Following a separate issue from: https://github.com/wbond/package_control/issues/890#issuecomment-355519346 (Handling Packages that Override Built In Packages)

All the `Package Control` unit tests should be passing:
<details>
<p>

```
Running Package Control Tests

EEEEEE........F.............E...........F..F................
======================================================================
ERROR: test_github_client_branch_downloads (Package Control.package_control.tests.clients.GitHubClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.clients in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 85, in test_github_client_branch_downloads
  File "package_control.clients.github_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 127, in download_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/repos/packagecontrol-test/package_control-tester/commits?sha=master&per_page=1&client_secret=&client_id=.

======================================================================
ERROR: test_github_client_repo_info (Package Control.package_control.tests.clients.GitHubClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.clients in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 40, in test_github_client_repo_info
  File "package_control.clients.github_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 169, in repo_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/repos/packagecontrol-test/package_control-tester?client_secret=&client_id=.

======================================================================
ERROR: test_github_client_tags_downloads (Package Control.package_control.tests.clients.GitHubClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.clients in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 113, in test_github_client_tags_downloads
  File "package_control.clients.github_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 94, in download_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/repos/packagecontrol-test/package_control-tester/tags?per_page=100&client_secret=&client_id=.

======================================================================
ERROR: test_github_client_tags_prefix_downloads (Package Control.package_control.tests.clients.GitHubClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.clients in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 126, in test_github_client_tags_prefix_downloads
  File "package_control.clients.github_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 94, in download_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/repos/packagecontrol-test/package_control-tester/tags?per_page=100&client_secret=&client_id=.

======================================================================
ERROR: test_github_client_user_info (Package Control.package_control.tests.clients.GitHubClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.clients in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in test_github_client_user_info
  File "package_control.clients.github_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 213, in user_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/users/packagecontrol-test/repos?client_secret=&client_id=.

======================================================================
ERROR: test_github_readme (Package Control.package_control.tests.clients.GitHubClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.clients in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 71, in test_github_readme
  File "package_control.clients.readme_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 64, in readme_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/repos/packagecontrol-test/package_control-tester/readme?ref=master&client_secret=&client_id=.

======================================================================
ERROR: test_get_packages (Package Control.package_control.tests.providers.GitHubUserProviderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.providers in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 155, in test_get_packages
  File "package_control.tests.providers in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 155, in <listcomp>
  File "package_control.providers.github_user_provider in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 142, in get_packages
  File "package_control.providers.github_user_provider in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 138, in get_packages
  File "package_control.clients.github_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 213, in user_info
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in fetch_json
  File "package_control.clients.json_api_client in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 42, in fetch
  File "package_control.download_manager in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 683, in download
Package Control.package_control.downloaders.downloader_exception.DownloaderException: Error downloading repository. HTTP error 403 downloading https://api.github.com/users/packagecontrol-test/repos?client_secret=&client_id=.

======================================================================
FAIL: test_get_packages (Package Control.package_control.tests.providers.GitHubRepositoryProviderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.providers in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 80, in test_get_packages
AssertionError: Lists differ: [('package_control-tester', {'... != []

First list contains 1 additional elements.
First extra element 0:
('package_control-tester', {'last_modified': '2014-11-28 20:54:15', 'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.', 'buy': None, 'previous_names': [], 'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues', 'sources': ['https://github.com/packagecontrol-test/package_control-tester'], 'homepage': 'https://github.com/packagecontrol-test/package_control-tester', 'releases': [{'sublime_text': '*', 'date': '2014-11-28 20:54:15', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/master', 'version': '2014.11.28.20.54.15'}], 'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md', 'author': 'packagecontrol-test', 'labels': [], 'name': 'package_control-tester', 'donate': None})

+ []
- [('package_control-tester',
-   {'author': 'packagecontrol-test',
-    'buy': None,
-    'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.',
-    'donate': None,
-    'homepage': 'https://github.com/packagecontrol-test/package_control-tester',
-    'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues',
-    'labels': [],
-    'last_modified': '2014-11-28 20:54:15',
-    'name': 'package_control-tester',
-    'previous_names': [],
-    'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md',
-    'releases': [{'date': '2014-11-28 20:54:15',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/master',
-                  'version': '2014.11.28.20.54.15'}],
-    'sources': ['https://github.com/packagecontrol-test/package_control-tester']})]

======================================================================
FAIL: test_get_packages_20_github (Package Control.package_control.tests.providers.RepositoryProviderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.providers in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 589, in test_get_packages_20_github
AssertionError: Lists differ: [('package_control-tester-2.0-... != []

First list contains 1 additional elements.
First extra element 0:
('package_control-tester-2.0-gh', {'last_modified': '2014-11-12 15:52:35', 'labels': [], 'buy': None, 'previous_names': [], 'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues', 'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-2.0-github_details.json', 'https://github.com/packagecontrol-test/package_control-tester'], 'homepage': 'https://github.com/packagecontrol-test/package_control-tester', 'releases': [{'sublime_text': '<3000', 'date': '2014-11-12 15:52:35', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1', 'version': '1.0.1'}, {'sublime_text': '<3000', 'date': '2014-11-12 15:14:23', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1-beta', 'version': '1.0.1-beta'}, {'sublime_text': '<3000', 'date': '2014-11-12 15:14:13', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.0', 'version': '1.0.0'}, {'sublime_text': '<3000', 'date': '2014-11-12 02:02:22', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/0.9.0', 'version': '0.9.0'}], 'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md', 'author': 'packagecontrol-test', 'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.', 'name': 'package_control-tester-2.0-gh', 'donate': None})

+ []
- [('package_control-tester-2.0-gh',
-   {'author': 'packagecontrol-test',
-    'buy': None,
-    'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.',
-    'donate': None,
-    'homepage': 'https://github.com/packagecontrol-test/package_control-tester',
-    'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues',
-    'labels': [],
-    'last_modified': '2014-11-12 15:52:35',
-    'name': 'package_control-tester-2.0-gh',
-    'previous_names': [],
-    'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md',
-    'releases': [{'date': '2014-11-12 15:52:35',
-                  'platforms': ['*'],
-                  'sublime_text': '<3000',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1',
-                  'version': '1.0.1'},
-                 {'date': '2014-11-12 15:14:23',
-                  'platforms': ['*'],
-                  'sublime_text': '<3000',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1-beta',
-                  'version': '1.0.1-beta'},
-                 {'date': '2014-11-12 15:14:13',
-                  'platforms': ['*'],
-                  'sublime_text': '<3000',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.0',
-                  'version': '1.0.0'},
-                 {'date': '2014-11-12 02:02:22',
-                  'platforms': ['*'],
-                  'sublime_text': '<3000',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/0.9.0',
-                  'version': '0.9.0'}],
-    'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-2.0-github_details.json',
-                'https://github.com/packagecontrol-test/package_control-tester']})]

======================================================================
FAIL: test_get_packages_300_github (Package Control.package_control.tests.providers.RepositoryProviderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "package_control.tests.providers in C:\Users\Professional\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 989, in test_get_packages_300_github
AssertionError: Lists differ: [('package_control-tester-3.0.... != []

First list contains 4 additional elements.
First extra element 0:
('package_control-tester-3.0.0-gh-tags', {'last_modified': '2014-11-12 15:52:35', 'labels': [], 'buy': None, 'previous_names': [], 'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues', 'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-3.0.0-github_releases.json', 'https://github.com/packagecontrol-test/package_control-tester'], 'homepage': 'https://github.com/packagecontrol-test/package_control-tester', 'releases': [{'sublime_text': '*', 'date': '2014-11-12 15:52:35', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1', 'version': '1.0.1'}, {'sublime_text': '*', 'date': '2014-11-12 15:14:23', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1-beta', 'version': '1.0.1-beta'}, {'sublime_text': '*', 'date': '2014-11-12 15:14:13', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.0', 'version': '1.0.0'}, {'sublime_text': '*', 'date': '2014-11-12 02:02:22', 'platforms': ['*'], 'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/0.9.0', 'version': '0.9.0'}], 'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md', 'author': 'packagecontrol-test', 'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.', 'name': 'package_control-tester-3.0.0-gh-tags', 'donate': None})

+ []
- [('package_control-tester-3.0.0-gh-tags',
-   {'author': 'packagecontrol-test',
-    'buy': None,
-    'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.',
-    'donate': None,
-    'homepage': 'https://github.com/packagecontrol-test/package_control-tester',
-    'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues',
-    'labels': [],
-    'last_modified': '2014-11-12 15:52:35',
-    'name': 'package_control-tester-3.0.0-gh-tags',
-    'previous_names': [],
-    'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md',
-    'releases': [{'date': '2014-11-12 15:52:35',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1',
-                  'version': '1.0.1'},
-                 {'date': '2014-11-12 15:14:23',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1-beta',
-                  'version': '1.0.1-beta'},
-                 {'date': '2014-11-12 15:14:13',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.0',
-                  'version': '1.0.0'},
-                 {'date': '2014-11-12 02:02:22',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/0.9.0',
-                  'version': '0.9.0'}],
-    'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-3.0.0-github_releases.json',
-                'https://github.com/packagecontrol-test/package_control-tester']}),
-  ('package_control-tester-3.0.0-gh-tags_base',
-   {'author': 'packagecontrol',
-    'buy': None,
-    'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.',
-    'donate': None,
-    'homepage': 'https://github.com/packagecontrol-test/package_control-tester',
-    'issues': None,
-    'labels': [],
-    'last_modified': '2014-11-12 15:52:35',
-    'name': 'package_control-tester-3.0.0-gh-tags_base',
-    'previous_names': [],
-    'readme': None,
-    'releases': [{'date': '2014-11-12 15:52:35',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1',
-                  'version': '1.0.1'},
-                 {'date': '2014-11-12 15:14:23',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.1-beta',
-                  'version': '1.0.1-beta'},
-                 {'date': '2014-11-12 15:14:13',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/1.0.0',
-                  'version': '1.0.0'},
-                 {'date': '2014-11-12 02:02:22',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/0.9.0',
-                  'version': '0.9.0'}],
-    'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-3.0.0-github_releases.json']}),
-  ('package_control-tester-3.0.0-gh-tags_prefix',
-   {'author': 'packagecontrol-test',
-    'buy': None,
-    'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.',
-    'donate': None,
-    'homepage': 'https://github.com/packagecontrol-test/package_control-tester',
-    'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues',
-    'labels': [],
-    'last_modified': '2014-11-28 20:54:15',
-    'name': 'package_control-tester-3.0.0-gh-tags_prefix',
-    'previous_names': [],
-    'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md',
-    'releases': [{'date': '2014-11-28 20:54:15',
-                  'platforms': ['windows'],
-                  'sublime_text': '<3000',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/win-1.0.2',
-                  'version': '1.0.2'}],
-    'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-3.0.0-github_releases.json',
-                'https://github.com/packagecontrol-test/package_control-tester']}),
-  ('package_control-tester-3.0.0-gh-branch',
-   {'author': 'packagecontrol-test',
-    'buy': None,
-    'description': 'A test of Package Control upgrade messages with explicit versions, but date-based releases.',
-    'donate': None,
-    'homepage': 'https://github.com/packagecontrol-test/package_control-tester',
-    'issues': 'https://github.com/packagecontrol-test/package_control-tester/issues',
-    'labels': [],
-    'last_modified': '2014-11-28 20:54:15',
-    'name': 'package_control-tester-3.0.0-gh-branch',
-    'previous_names': [],
-    'readme': 'https://raw.githubusercontent.com/packagecontrol-test/package_control-tester/master/readme.md',
-    'releases': [{'date': '2014-11-28 20:54:15',
-                  'platforms': ['*'],
-                  'sublime_text': '*',
-                  'url': 'https://codeload.github.com/packagecontrol-test/package_control-tester/zip/master',
-                  'version': '2014.11.28.20.54.15'}],
-    'sources': ['https://raw.githubusercontent.com/wbond/package_control-json/master/repository-3.0.0-github_releases.json',
-                'https://github.com/packagecontrol-test/package_control-tester']})]

----------------------------------------------------------------------
Ran 60 tests in 22.646s

FAILED (failures=3, errors=7)
```
</p>
</details><br>

Errors and failures are only for the GitHub URL accesses, probably related to:

https://github.com/wbond/package_control/blob/1f551cc92afb95ba5ca4cd17270060de4f796ea1/package_control/tests/__init__.py#L9-L13

How I am supposed to run the GitHub tests?

**Comment by deathaxe** [comment]
Github now requires the user-agent to be available in the http headers, which is not the case in the tests. Therefore github returns an error instead of the requested file content.

**Comment by evandrocoan** [comment]
Thanks! I am not familiar with this but it seems simple add this.

Then is not actually required the ´CLIENT_ID´ and `CLIENT_SECRET` unless the tests starts going over the GitHub anonymous API accesses.

**Comment by evandrocoan** [comment]
All tests have passed on Travis' Linux and AppVeyor's Windows:

1. https://travis-ci.org/evandrocoan/PackagesManager/jobs/326417834
1. https://ci.appveyor.com/project/evandrocoan/packagesmanager/build/1.0.16

Except on Travis' OSX, where the tests are hanging on about at the penultimate test:

1. https://github.com/SublimeText/UnitTesting/issues/78 Travis OSX build is halting
