### ISSUE TITLE
Can't install a package with package control

### ISSUE THREAD

**Issue by SakisHous** [wbond/package_control#1352]
I was trying to install some packages in Sublime Text 3. I followed the descriptions [https://packagecontrol.io/installation](url) . Although, when I get the dialog with Ctrl+Shift+P and type install packages, it appears a list of them. I choose one and I wait to install in the Sublime Text 3. Although, I get the following error from the console.

Traceback (most recent call last):
  File "package_control.package_installer in C:\Users\Sakis\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 154, in on_done
  File "package_control.package_disabler in C:\Users\Sakis\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 76, in disable_packages
ImportError: No module named 'package_control'

I cannot figure out the problem and fix it. Do you have any idea?

**Comment by dwasss** [comment]
Sounds like you may need to reinstall Package Control.
