### ISSUE TITLE
flake8 pkg not working with sublimetext3 

### ISSUE THREAD

**Issue by jayanthswami** [wbond/package_control#1356]
Getting this error while flake8 is run on my py script after saving it, Can some on give any inputs on this ?

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\Flake8Lint.py", line 1164, in <lambda>
    lambda: Flake8Lint.async_lint(view, view_settings, quiet=quiet), 0
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\Flake8Lint.py", line 1221, in async_lint
    interpreter, linter)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\lint.py", line 347, in lint_external
    startupinfo=startupinfo
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
ERROR:root:Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
The OS did return [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\Flake8Lint.py", line 1164, in <lambda>
    lambda: Flake8Lint.async_lint(view, view_settings, quiet=quiet), 0
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\Flake8Lint.py", line 1221, in async_lint
    interpreter, linter)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\lint.py", line 347, in lint_external
    startupinfo=startupinfo
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by FichteFoll** [comment]
You should have taken a look at the package's github page, which is https://github.com/dreadatour/Flake8Lint. It states that the package is abandoned and recommends using SublimeLinter and SublimeLintre-flake8 instead.
