### ISSUE TITLE
UnicodeEncodeError in package_manager.py

### ISSUE THREAD

**Issue by tomikais** [wbond/package_control#1381]
Hi,

running Ubuntu 18.04 in VirtualBox. When I try to Install Packages I receive the following error:
Exception in thread Thread-5:
```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/ruth/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/home/ruth/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 91, in make_package_list
    if self.manager.is_vcs_package(package):
  File "/home/ruth/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 310, in is_vcs_package
    return self._is_git_package(package) or self._is_hg_package(package)
  File "/home/ruth/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 285, in _is_git_package
    return os.path.exists(git_dir) and (os.path.isdir(git_dir) or os.path.isfile(git_dir))
  File "./python3.3/genericpath.py", line 18, in exists
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 49: ordinal not in range(256)
```

Kind regards, Thomas

**Comment by j-yost** [comment]
I get the same error when trying to run "Install Package" on a new Linux installation of SublimeText3.1.1 Build3171
-----------------------------------------------
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/yostj/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/home/yostj/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 91, in make_package_list
    if self.manager.is_vcs_package(package):
  File "/home/yostj/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 310, in is_vcs_package
    return self._is_git_package(package) or self._is_hg_package(package)
  File "/home/yostj/.config/sublime-text-3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 285, in _is_git_package
    return os.path.exists(git_dir) and (os.path.isdir(git_dir) or os.path.isfile(git_dir))
  File "./python3.3/genericpath.py", line 18, in exists
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 50: ordinal not in range(256)

**Comment by FichteFoll** [comment]
Try running Sublime Text with `LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 sublime_text`.

**Comment by tomikais** [comment]
@FichteFoll thank you for your fix! After set locale permanently its working:
`sudo locale-gen en_US.UTF-8`
`sudo update-locale LANG=en_US.UTF-8`
`sudo reboot`

**Comment by sandeep2244** [comment]
@FichteFoll  its not working for me
