### ISSUE TITLE
Package control is down.

### ISSUE THREAD

**Issue by lcpriest** [wbond/package_control#1396]
See the website:
https://packagecontrol.io/search/vue

My error log:

```
startup, version: 3176 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/lachlanpriest/Library/Application Support/Sublime Text 3/Packages
state path: /Users/lachlanpriest/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/lachlanpriest/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
Errors parsing theme:
icon_folder_loading is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.734052
using gpu buffer for window
startup time: 0.823156
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin Automatic Backups.AutomaticBackups
reloading plugin Automatic Backups.backup_paths
reloading plugin Automatic Backups.backups_navigator
reloading plugin Automatic Backups.settings
reloading plugin Automatic Backups.win32helpers
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/lachlanpriest/Library/Application Support/Sublime Text 3/Installed Packages/Automatic Backups.sublime-package/win32helpers.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "./python3.3/ctypes/wintypes.py", line 20, in <module>
ValueError: _type_ 'v' not supported
reloading plugin Boxy Theme.BT
reloading plugin Boxy Theme.Icons
reloading plugin CSV.csvplugin
reloading plugin Elixir.mix_format_file
reloading plugin ERB Autocomplete.erb_autocomplete
reloading plugin ESLint-Formatter.ESLint-Formatter
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin GitHubinator.githubinator
reloading plugin HTMLBeautify.HTMLBeautify
reloading plugin Javascript Beautify.jsbeautify
reloading plugin JSON Reindent.sublime_json_reindent
reloading plugin MarkdownPreview.markdown_preview
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Python Checker.__main__
reloading plugin Python Checker.checker
reloading plugin Python Checker.plugin
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-stylelint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Babel.Babel
reloading plugin BeautifyRuby.beautify_ruby
reloading plugin BetterFindBuffer.find_results
reloading plugin ESLint.ESLint
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin Stylefmt.node_bridge
reloading plugin Stylefmt.Stylefmt
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2019-01-11 11:43:10, next run at 2019-01-11 12:43:10 or after
Package Control: Error downloading channel. HTTP error 404 downloading https://packagecontrol.io/channel_v3.json.
```

**Comment by wbond** [comment]
You shouldn't get a 404 anymore, but the server did suffer some file system corruption, so it will likely be degraded for a while as I pick up the pieces.

**Comment by lcpriest** [comment]
Thanks!
