### ISSUE TITLE
UnicodeEncodeError Exception while fetching package list

### ISSUE THREAD

**Issue by OdatNurd** [wbond/package_control#1410]
### Description

The code in the `_is_git_package()` method in `package_manager.py` uses the name of a package to see if there is a git installed version of that package already. If the package contains characters not supported by the system's encoding, this results in `UnicodeEncodeError` being thrown. 

This method is invoked when using `Package Control: Install Package`, with the net result being that it's impossible to install any packages, even in a clean installation of Sublime.

I've only ever noticed this on Linux, where my distribution's default language is `en_US` and not `en_US.utf-8`, which causes it to use the `latin-1` encoding. I'm not sure if the same thing could also happen on MacOS or Windows if the system language was suitably set. 

In particular, the [Okami – Adaptive Color Schemes](https://github.com/wbond/package_control_channel/blob/master/repository/o.json#L248-L258) package in the default channel uses an extended dash character in its name. The addition of this package is what originally tripped this error for me. 

### Reproduction Steps

1.  Start Sublime from a Linux terminal with `LANG=en_US ./sublime_text` to set the encoding to `latin-1`.

2. Invoke the `Package Control: Install Package` command

### Exception

```plain
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/tmp/bob/sublime_text_3_3190/Data/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/tmp/bob/sublime_text_3_3190/Data/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 91, in make_package_list
    if self.manager.is_vcs_package(package):
  File "/tmp/bob/sublime_text_3_3190/Data/Packages/Package Control/package_control/package_manager.py", line 310, in is_vcs_package
    return self._is_git_package(package) or self._is_hg_package(package)
  File "/tmp/bob/sublime_text_3_3190/Data/Packages/Package Control/package_control/package_manager.py", line 285, in _is_git_package
    return os.path.exists(git_dir) and (os.path.isdir(git_dir) or os.path.isfile(git_dir))
  File "./python3.3/genericpath.py", line 18, in exists
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 49: ordinal not in range(256)
```

### Debug Log

```plain
Package Control: Fetching list of available packages and dependencies
  Platform: linux-x64
  Sublime Text Version: 3190
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 74.207.232.232
  Resolved IPv6: 2600:3c02::f03c:91ff:fec5:4fd5
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found system CA bundle at /etc/ssl/certs/ca-certificates.crt (245542 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /tmp/bob/sublime_text_3_3190/Data/Packages/User/Package Control.merged-ca-bundle
  Using hostname "packagecontrol.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-GCM-SHA256
  Server SSL certificate:
    subject: CN=packagecontrol.io
    subject alt name: packagecontrol.io, www.packagecontrol.io
    expire date: Nov 27 12:00:00 2019 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  Connection: Keep-Alive
  User-Agent: Package Control v3.3.0
  If-None-Match: "5c6d82e4-53150"
  Host: packagecontrol.io
  If-Modified-Since: Wed, 20 Feb 2019 16:40:04 GMT
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Wed, 20 Feb 2019 16:44:45 GMT
  Content-Type: application/json
  Last-Modified: Wed, 20 Feb 2019 16:40:04 GMT
  Connection: keep-alive
  ETag: "5c6d82e4-53150"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /tmp/bob/sublime_text_3_3190/Data/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
```

**Comment by wbond** [comment]
This should hopefully now be detected as of b06eedf82f872c54685661f9d57d28abd5221946
