### ISSUE TITLE
plugin_host crashes on Linux with libssl.so.1.1 and Package Control

### ISSUE THREAD

**Issue by evandrocoan** [wbond/package_control#1412]
Moved from: https://github.com/SublimeTextIssues/Core/issues/2644 plugin_host crashes on Linux with libssl.so.1.1 and Package Control

### Description

After a afternoon debugging it, the crash happens when this function is called on the Package Control code:
```python
File: package_control/deps/oscrypto/_openssl/tls.py
166:             if libcrypto_version_info < (1, 1):
167:                 method = libssl.SSLv23_method()
168:             else:
169:                 method = libssl.TLS_method()
170:             ssl_ctx = libssl.SSL_CTX_new(method) # This line causes `plugin_host` to crash
```
1. https://github.com/wbond/package_control/blob/db53090bd0920ca2c58ef27f0361a4d7b096df0e/package_control/deps/oscrypto/_openssl/tls.py#L166-L170

These lines are the current code on the master branch of Package Control. These lines are not yet released to everybody because the latest git tag/version is several commits before the addition of `oscrypto` dependency. Therefore, crash only happens when Package Control is installed by git with `git clone`. If Package Control is installed as `Package Control.sublime-package`, i.e, from the latest tag not the master branch, everything works fine.

The `SSL_CTX_new` documentation can be found here:
1. https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_new.html

This issue is Linux Only with `/usr/lib/x86_64-linux-gnu/libssl.so.1.1` installed and used by `oscrypto`.

### Steps to reproduce

1. Delete `~/.config/sublime-text-3/` (super clean install)
1. Run the command `git clone https://github.com/wbond/package_control "~/.config/sublime-text-3/Packages/Package Control"`
1. Delete `~/.config/sublime-text-3/Packages/User/Package Control.last-run` (if it exists `plugin_host` does not crash, because the line `ssl_ctx = libssl.SSL_CTX_new(method)` is not run)
1. Open Sublime Text and wait for `plugin_host` to crash
1. Log entry on `/var/log/syslog`: `24 18:25:12 linux kernel: [71315.331384] plugin_host[71972]: segfault at 0 ip 00007f13975f1e8a sp 00007f138d0b4ff8 error 4 in libc-2.27.so[7f1397548000+1e7000]`
1. Stack trace on Package Control until the line ` ssl_ctx = libssl.SSL_CTX_new(method)`:
   ```
   plugins loaded
   Exception in thread Thread-7:
   Traceback (most recent call last):
     File "./python3.3/threading.py", line 901, in _bootstrap_inner
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/automatic_upgrader.py", line 117, in run
       self.upgrade_packages()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/automatic_upgrader.py", line 247, in upgrade_packages
       self.package_renamer.rename_packages(self.installer)
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/package_renamer.py", line 36, in rename_packages
       installer.manager.list_available_packages()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/package_manager.py", line 694, in list_available_packages
       return self._list_available()[0]
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/package_manager.py", line 554, in _list_available
       repositories = self.list_repositories()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/package_manager.py", line 453, in list_repositories
       channel_repositories = provider.get_repositories()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/providers/channel_provider.py", line 201, in get_repositories
       self.fetch()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/providers/channel_provider.py", line 87, in fetch
       channel_json = manager.fetch(self.channel, 'Error downloading channel.')
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/download_manager.py", line 344, in fetch
       return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/downloaders/oscrypto_downloader.py", line 119, in download
       reused = self.setup_connection(url, timeout)
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/downloaders/oscrypto_downloader.py", line 317, in setup_connection
       return self.ensure_connected()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/downloaders/oscrypto_downloader.py", line 324, in ensure_connected
       reused = self.setup_socket()
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/downloaders/oscrypto_downloader.py", line 354, in setup_socket
       session = tls.TLSSession(extra_trust_roots=extra_trust_roots)
     File "/home/linux/.config/sublime-text-3/Packages/Package Control/package_control/deps/oscrypto/_openssl/tls.py", line 170, in __init__
        ssl_ctx = libssl.SSL_CTX_new(method)
   ```

### Expected behavior

Not crash `plugin_host` is Package Control is installed by `git clone`.

### Actual behavior

Crash `plugin_host` is Package Control is installed by `git clone`.

### Environment

* Build: `3176 (x64)`
* Operating system and version: `Linux Mint 19.1 XFCE, 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* [Linux] Desktop Environment and/or Window Manager: `XFCE4`

**Comment by wbond** [comment]
My hunch is a conflict between having OpenSSL 1.02 statically linked into `plugin_host` for the `_ssl` module, and `oscrypto` trying to `dlopen()` OpenSSL 1.1 from the OS.

I'm not sure if there is a work-around here. I've seen some complicated/seemingly insurmountable bugs in the cryptography package for Python dealing with stuff like this.

It may just be that `oscrypto` won't be usable with the Python 3.3 `plugin_host`, but perhaps will work with the new Python 3.8 `plugin_host` since that dynamically opens OpenSSL 1.1 from the install dir, and oscrypto can be configured to load the same version of OpenSSL.

**Comment by wbond** [comment]
As of fbf9b496bdf937a8f85dc33f8ab00c449fa28720 this should be fixed
