### ISSUE TITLE
The dependency "paramiko" is either not available on this platform or for this version of Sublime Text

### ISSUE THREAD

**Issue by Aethylred** [wbond/package_control#1425]
Creating a new ticket as per #989 

Running Sublime Text 3 and Package Control on Windows 10, every time Sublime Text 3 is started I get a dialogue with the text "1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly."

This is the startup log.

```
DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/hicksaw/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/hicksaw/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/hicksaw/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Makefile", "Vintage"]
pre session restore time: 0.377265
startup time: 0.449265
first paint time: 0.451265
git: tracking working dir C:\Development\Python\pyspectrumscale
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-python-six
reloading plugin 0_package_control_loader.08-portalockerfile
reloading plugin 0_package_control_loader.09-concurrentloghandler
reloading plugin 0_package_control_loader.10-debugtools
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-enum
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-plantumlconnection
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-python-pywin32
python-pywin32: Added 'win32com'
python-pywin32: Added 'win32'
python-pywin32: Added 'win32/lib'
python-pywin32: Added 'win32comext'
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-pyzmq
reloading plugin 0_package_control_loader.50-typing
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Boxy Theme.BT
reloading plugin Boxy Theme.Icons
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin DoxyDoxygen.Doxy
------==== DoxyDoxygen plugins loaded ====------
0 sub-modules to reload
reloading plugin Git blame.git-blame
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin GitHub Flavored Markdown Preview.GHMarkdownPreview
reloading plugin GitStatusBar.git_status_bar
reloading plugin Graphvizer.graphvizer
reloading plugin Graphvizer.graphvizer_panel
reloading plugin Graphvizer.syntaxchecker
reloading plugin Hermes.__init__
reloading plugin Hermes.hermes
reloading plugin Hermes.kernel
reloading plugin Hermes.utils
reloading plugin Line Endings Unify.LineEndingsUnify
reloading plugin Makefile Improved.Makefile Improved
reloading plugin Markdown HTML Preview.MarkdownHtmlPreview
reloading plugin MarkdownCodeBlockWrapper.MdCodeBlock
reloading plugin MarkdownPreview.markdown_preview
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin MarkdownTOC.__init__
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Materialize.Materialize
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PlantUmlDiagrams.diagram_plugin
reloading plugin Python Checker.__main__
reloading plugin Python Checker.checker
reloading plugin Python Checker.plugin
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-contrib-ansible-lint.linter
ansiblelint: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
ansiblelint: Defining 'cls.selectors' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
ansiblelint: Defining 'cls.version_args' has no effect. Please cleanup and remove these settings.
ansiblelint: Defining 'cls.version_re' has no effect. Please cleanup and remove these settings.
ansiblelint: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
ansiblelint: Defining 'cls.inline_settings' has no effect. Please cleanup and remove these settings.
ansiblelint: Defining 'cls.inline_overrides' has no effect. Please cleanup and remove these settings.
ansiblelint: Defining 'cls.comment_re' has no effect. Please cleanup and remove these settings.
reloading plugin SublimeLinter-contrib-bashate.linter
reloading plugin SublimeLinter-contrib-cheetah-flake.linter
cheetahflake: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
cheetahflake: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
reloading plugin SublimeLinter-contrib-puppet-lint.linter
puppetlint: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
reloading plugin SublimeLinter-contrib-puppet.linter
puppet: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
reloading plugin SublimeLinter-contrib-yamllint.linter
yamllint: Defining 'cls.version_args' has no effect. Please cleanup and remove these settings.
yamllint: Defining 'cls.version_re' has no effect. Please cleanup and remove these settings.
yamllint: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pyflakes.linter
reloading plugin SublimeLinter-pylint.linter
reloading plugin SublimeLinter-ruby.linter
ruby: Defining 'cls.comment_re' has no effect. Please cleanup and remove these settings.
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Whitespace.Whitespace
reloading plugin Bats.bats
reloading plugin concurrentloghandler.setup
reloading plugin debugtools.setup
reloading plugin plantumlconnection.setup
reloading plugin portalockerfile.setup
reloading plugin SublimeLinter-contrib-perlcritic.linter
reloading plugin SublimeLinter-rst.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\hicksaw\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-rst\linter.py", line 15, in <module>
    import docutils
ImportError: No module named 'docutils'
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
user_preferences_file: C:\Users\hicksaw\AppData\Roaming\Sublime Text 3\Packages\User\Preferences.sublime-settings
s: {
	"binary_file_patterns":
	[
		"venv/*",
		"alembic/*"
	],
	"bold_folder_labels": true,
	"caret_extra_bottom": 2,
	"caret_extra_top": 2,
	"caret_extra_width": 3,
	"caret_style": "phase",
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
	"default_line_ending": "unix",
	"folder_exclude_patterns":
	[
		".git",
		".venv",
		"venv"
	],
	"font_face": "Hack",
	"font_size": 13,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Makefile",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"indent_to_bracket": true,
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"show_encoding": true,
	"smart_indent": true,
	"tab_size": 4,
	"theme": "Afterglow.sublime-theme",
	"translate_tabs_to_spaces": true,
	"wide_caret": true
}

Package Control: Installing 1 missing dependency
Package Control: The dependency "paramiko" is either not available on this platform or for this version of Sublime Text
Package Control: Installed missing dependency paramiko
Package Control: Skipping automatic upgrade, last run at 2019-04-23 13:03:07, next run at 2019-04-23 14:03:07 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

**Comment by FichteFoll** [comment]
`paramiko` is only available for macOS ([source](https://github.com/wbond/package_control_channel/blob/8d5f9eaeac9c9590ae3fb2882f37250d5df8a055/repository/dependencies.json#L562). Most likely some package incorrectly specifies it for all platforms.

**Comment by Aethylred** [comment]
In which case the problem is we're not getting sufficient dependency error information to figure which package we've installed has a dependency on another package that is throwing errors. If we're provided sufficient dependency information then we are able to decide between:

- do nothing and put up with the problem
- remove the package with the broken dependency
- raise an issue with the maintainers of the package with the broken dependency

Without this information we're stuck with doing nothing, or raising issues here :)

**Comment by Aethylred** [comment]
Alternativly, for this specific error `Package Control: The dependency "XXXX" is either not available on this platform or for this version of Sublime Text` maybe not popping up a dialogue box...

**Comment by RCJacH** [comment]
I found out through searching file content that it was a packaged called **pyzmq** that requires paramiko which is unable to install on windows. However I could not find what is required to install pyzmq. Native maybe?
I tried deleting it but just ended up reinstalling when starting up sublime text.

**Comment by FichteFoll** [comment]
Dependencies cannot specify dependencies themselves.
