### ISSUE TITLE
"1 Missing Dependency" Error on launch after recent update

### ISSUE THREAD

**Issue by TheJaredWilcurt** [wbond/package_control#1427]
**OS:** Win 10 64-Bit
**Version:** Dev Channel, Build 3208

Recent update to Sublime now causes an error message every time it is open, about 20 seconds after launching.

![err](https://user-images.githubusercontent.com/4629794/56669484-335b1e00-667f-11e9-8d1f-4727f9ab39e0.png)

**Console log after launching and error occurs:**
```
DPI mode: per-monitor (w/ non-client)
startup, version: 3208 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/owner/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/owner/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/owner/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.274396
Unable to parse color value #a9bbc at Packages/Theme - Legacy/Widgets.stTheme:unknown
startup time: 0.402396
first paint time: 0.402396
scan: /C/Users/owner/Documents/GitHub/atc-inventory-api/node_modules/sequelize-handlers has been seen before, skipping (using inode) previous path: /C/Users/owner/Documents/GitHub/atc-inventory-api/lib/sequelize-handlers inode: 4222124651955459
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin Discord Rich Presence._logging
reloading plugin Discord Rich Presence.drp
reloading plugin DocBlockr.jsdocs
reloading plugin EditorConfig.EditorConfig
reloading plugin MoveTab.move_tab
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin Sass.sass_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin BufferScroll.BufferScroll
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\owner\AppData\Roaming\Sublime Text 3\Packages\BufferScroll\BufferScroll.py", line 22, in <module>
    from debug_tools import getLogger
ImportError: No module named 'debug_tools'
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin PythonDebugTools.setup
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: The dependency "PythonDebugTools" is either not available on this platform or for this version of Sublime Text
Package Control: Installed missing dependency PythonDebugTools
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
Package Control: No updated packages
```

**Installed plugins:**

![plugins](https://user-images.githubusercontent.com/4629794/56669634-73220580-667f-11e9-9a32-69a7b15657ec.png)

All installed via package control except Buffer Scroll which was installed manually.

**Comment by FichteFoll** [comment]
As I mentioned on Discord, [https://github.com/wbond/package_control_channel/commit/cee00101460f8c32fee559f44b97314645a9c00d](this is the issue).

Some package that you installed and that uses the dependency must not have been updated to the new name.
