### ISSUE TITLE
Unable to install any packages with wget

### ISSUE THREAD

**Issue by King-ofwolf** [wbond/package_control#1434]
Opration system is Ubuntu 16.04.5 LTS.
Sublime Text 3 version is Stable Channel, Build 3126.
I have set the Package Control.sublime-settings as:
`"channels":
	[
		"http://cst.stu.126.net/u/json/cms/channel_v3.json"
	],
	"downloader_precedence":
	{
		"linux":
		[
			"wget",
			"curl",
			"urllib"
		]
	},
`
because my opration system is unable to install curl and no command named curl.
But I cannot install any packages now with some Exceptions:

> Exception in thread Thread-18:
Traceback (most recent call last):
  File "package_control.downloaders.wget_downloader in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 154, in download
  File "package_control.downloaders.cli_downloader in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 85, in execute
Package Control.package_control.downloaders.non_clean_exit_error.NonCleanExitError: 4

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_installer in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 202, in run
  File "package_control.package_manager in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 1115, in install_package
  File "package_control.download_manager in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.wget_downloader in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 167, in download
  File "package_control.downloaders.wget_downloader in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 305, in parse_output
  File "package_control.downloaders.wget_downloader in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 351, in parse_headers
  File "package_control.open_compat in /home/wangshengling/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 14, in open_compat
Package Control.package_control.file_not_found_error.FileNotFoundError: The file "/tmp/tmpysnja_" could not be found

**Comment by wbond** [comment]
What happens if you try to use wget to download https://packagecontrol.io/channel_v3.json on the command line?
