### ISSUE TITLE
Package Control not working in OS Catalina

### ISSUE THREAD

**Issue by yxryxryxr3** [wbond/package_control#1451]
When I input ctrl + shift + P and click Package Control: Installing packages in mac os 10.15 Catalina, and it throw an exception as below.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/automatic_upgrader.py", line 111, in run
    self.install_missing()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/automatic_upgrader.py", line 176, in install_missing
    self.manager.list_available_packages()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 694, in list_available_packages
    return self._list_available()[0]
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 166, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache, cert_callback=print_cert_subject)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 122, in get_path
    for cert, trust_oids, reject_oids in extract_from_system(cert_callback):
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 51, in extract_from_system
    handle_sec_error(res)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_security.py", line 50, in handle_sec_error
    raise exception_class(output)
OSError: The specified item could not be found in the keychain.

Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 58, in make_package_list
    packages = self.manager.list_available_packages()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 694, in list_available_packages
    return self._list_available()[0]
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 166, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache, cert_callback=print_cert_subject)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 122, in get_path
    for cert, trust_oids, reject_oids in extract_from_system(cert_callback):
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 51, in extract_from_system
    handle_sec_error(res)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_security.py", line 50, in handle_sec_error
    raise exception_class(output)
OSError: The specified item could not be found in the keychain.

Exception in thread Thread-8:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 58, in make_package_list
    packages = self.manager.list_available_packages()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 694, in list_available_packages
    return self._list_available()[0]
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 340, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 166, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache, cert_callback=print_cert_subject)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 122, in get_path
    for cert, trust_oids, reject_oids in extract_from_system(cert_callback):
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 51, in extract_from_system
    handle_sec_error(res)
  File "/Users/yxr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_security.py", line 50, in handle_sec_error
    raise exception_class(output)
OSError: The specified item could not be found in the keychain.

**Comment by kontza** [comment]
Still problems with it? Try adding the following to `$HOME/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings`:
```
"downloader_precedence": {
  "osx": ["curl", "wget", "urllib"]
}
```
