### ISSUE TITLE
Package Control still does not work

### ISSUE THREAD

**Issue by will4378** [wbond/package_control#1452]
Package Control is not working in the Netherlands. Have I missed something?

**Comment by FichteFoll** [comment]
Does it still not work? You may need to refresh your dns cache.

**Comment by john-aws** [comment]
After DNS flush, still 404.

```
>>> import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Note that the reason that I am attempting to reinstall Package Control is that it was unable to install any new packages:

```
Package Control: Skipping automatic upgrade, last run at 2019-10-15 09:43:54, next run at 2019-10-15 10:43:54 or after
Package Control: Error downloading channel. URL error [Errno 61] Connection refused downloading https://packagecontrol.io/channel_v3.json.
```

Also note that I was able to get https://packagecontrol.io/channel_v3.json just fine from a browser earlier, but it now also reports connection refused.

**Comment by catch22** [comment]
I get connection refused with https and a "This domain was recently registered at Namecheap. Please check back later!" message when accessing via http (from NL).

**Comment by bhavyanshu** [comment]
I can confirm this from Chicago, US. I do see the Namecheap page.

**Comment by wbond** [comment]
Please report what IP you are getting for packagecontrol.io. Mostly likely the DNS system somewhere between the root servers and you has cached the IP when the domain was expired.

**Comment by catch22** [comment]
198.54.117.200

**Comment by wbond** [comment]
The correct IP (as of today) is **50.116.34.243**.

Querying Google's DNS servers gives:

```
wbond$ dig @8.8.8.8 packagecontrol.io

; <<>> DiG 9.10.6 <<>> @8.8.8.8 packagecontrol.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30767
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;packagecontrol.io.		IN	A

;; ANSWER SECTION:
packagecontrol.io.	154	IN	A	50.116.34.243

;; Query time: 51 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Oct 15 15:05:21 EDT 2019
;; MSG SIZE  rcvd: 62
```

**Comment by will4378** [comment]
Package Control is working again. Location Netherlands
