### ISSUE TITLE
MacOS Big Sur beta error with package control 

### ISSUE THREAD

**Issue by pak-gh** [wbond/package_control#1483]
I'm running Beta 3 of the new MacOS Big Sur on my new laptop. I needed to load Sublime and I wanted to load some of the packages I've used before. I cant install any packages as installing package control fails. 

Here is the log for the console. Any ideas on what I can try? 
Thanks so much! 

----------
tartup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/pk/Library/Application Support/Sublime Text 3/Packages
state path: /Users/pk/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/pk/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.355818
using gpu buffer for window
startup time: 0.584765
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
plugins loaded
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 7, in <module>
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/2_bootstrap.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/bootstrap.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation_ctypes.py", line 21, in <module>
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 7, in <module>
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/Package Control.py", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/advanced_install_package_command.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pk/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation_ctypes.py", line 21, in <module>
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
---------

**Comment by ShawnLiii** [comment]
Same system, same issue. Waiting for a solution to this issue. I would like to install a swift package.

**Comment by dofy** [comment]
Refer to the following link https://github.com/wbond/package_control/issues/1475#issuecomment-665180813

**Comment by TarekHolanda** [comment]
Thank you, @dofy. This solved my problem.

**Comment by wbond** [comment]
This should be fixed in master as of 32e44f70b6cf28f7071545a0d54b69be372f39ae

**Comment by dylanfrankcom** [comment]
> How do I generate `Package Control.sublime-package` from this repo?

Wondering the same thing.

**Comment by abowerman** [comment]
@dylanfrankcom Thank you much!

**Comment by Tekl** [comment]
In my case cloning the repo does not have any effect. I don't get a "Package Control" command and Sublime just offers "Install Package Control".

**Comment by TheSecEng** [comment]
@Tekl Yes those packages are correct.

Are you fully quitting ST?

## Steps

1. Launch ST
2. Ensure Package Control is uninstalled
3. Fully quit ST <kbd>⌘</kbd> + <kbd>Q</kbd>
4. Open Terminal.app
5. On of the following command blocks below depending on ST version
6. Launch ST and Open Console <kbd>⌃</kbd> + <kbd>`</kbd>
7. View for any errors
8. Report errors back here.


### ST3
```bash
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
git clone https://github.com/wbond/package_control.git Package\ Control
```

### ST 4000+
```bash
cd ~/Library/Application\ Support/Sublime\ Text/Packages
git clone https://github.com/wbond/package_control.git Package\ Control
```

**Comment by Tekl** [comment]
Uhhh ... thanks. I cloned into "Installed Packages". Now I understand, that it can't work.

**Comment by wbnns** [comment]
@dofy @dylanfrankcom Thanks you all, this fixed my problem.

**Comment by jererobles** [comment]
Anybody still facing the issue after following steps above, make sure you didn't accidentally ignore "Package Control" plugin in your Sublime Text settings file.

**Comment by debdebbie** [comment]
> @Tekl Yes those packages are correct.
> 
> Are you fully quitting ST?
> 
> ## Steps
> 1. Launch ST
> 2. Ensure Package Control is uninstalled
> 3. Fully quit ST ⌘ + Q
> 4. Open Terminal.app
> 5. On of the following command blocks below depending on ST version
> 6. Launch ST and Open Console ⌃ + `
> 7. View for any errors
> 8. Report errors back here.
> 
> ### ST3
> ```shell
> cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
> git clone https://github.com/wbond/package_control.git Package\ Control
> ```
> 
> ### ST 4000+
> ```shell
> cd ~/Library/Application\ Support/Sublime\ Text/Packages
> git clone https://github.com/wbond/package_control.git Package\ Control
> ```

startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages
state path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/stuartchloe/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.303922
using gpu buffer for window
startup time: 0.819129
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/2_bootstrap.py", line 26, in <module>
    from .package_control.bootstrap import bootstrap_dependency, mark_bootstrapped
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/bootstrap.py", line 20, in <module>
    from .download_manager import downloader
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/download_manager.py", line 24, in <module>
    from .downloaders import DOWNLOADERS
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/__init__.py", line 20, in <module>
    from .oscrypto_downloader import OscryptoDownloader
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/oscrypto_downloader.py", line 44, in <module>
    from ..deps.oscrypto import tls  # noqa
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/tls.py", line 11, in <module>
    from ._mac.tls import (
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_mac/tls.py", line 39, in <module>
    from .util import rand_bytes
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "./python3.3/ctypes/__init__.py", line 353, in __init__
OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/Package Control.py", line 89, in <module>
    from .package_control.commands import *  # noqa
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/commands/__init__.py", line 3, in <module>
    from .advanced_install_package_command import AdvancedInstallPackageCommand
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/commands/advanced_install_package_command.py", line 10, in <module>
    from ..package_manager import PackageManager
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 34, in <module>
    from .downloaders.background_downloader import BackgroundDownloader
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/__init__.py", line 20, in <module>
    from .oscrypto_downloader import OscryptoDownloader
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/oscrypto_downloader.py", line 44, in <module>
    from ..deps.oscrypto import tls  # noqa
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/tls.py", line 11, in <module>
    from ._mac.tls import (
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_mac/tls.py", line 39, in <module>
    from .util import rand_bytes
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/stuartchloe/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/deps/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "./python3.3/ctypes/__init__.py", line 353, in __init__
OSError: dlopen(/Users/stuartchloe/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
	/Users/stuartchloe/lib/libcrypto.dylib: mach-o, but wrong architecture
plugins loaded

Hi, after following the step to install package still having errors as above show
