### ISSUE TITLE
QuickPanelItem Issue with automatic_upgrader

### ISSUE THREAD

**Issue by TheSecEng** [wbond/package_control#1493]
Adding `QuickPanelItem` has introduced a bug in `automatic_upgrader.py`

```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/Terminal/Library/Application Support/Sublime Text/Packages/Package Control/package_control/automatic_upgrader.py", line 137, in run
    self.upgrade_packages()
  File "/Users/Terminal/Library/Application Support/Sublime Text/Packages/Package Control/package_control/automatic_upgrader.py", line 282, in upgrade_packages
    if package[0] != 'Package Control':
TypeError: 'QuickPanelItem' object does not support indexing
```

**Comment by jbergstroem** [comment]
Same issue, I believe: https://github.com/wbond/package_control/issues/1490

**Comment by TheSecEng** [comment]
@jbergstroem you are right. FYI I have a PR open to fix this.
