### ISSUE TITLE
Not able to install new packages

### ISSUE THREAD

**Issue by RMcGhee** [wbond/package_control#1514]
If you are running into a bug, please read https://packagecontrol.io/docs/troubleshooting
before submitting an issue here.

Bug reports must include a debug log. The Troubleshooting page explains how to capture one.

debug turned on, text captured after running Package Control: Install Package

Nothing happens after running Install Package.

Running macOS 11.1

startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/username/Library/Application Support/Sublime Text 3/Packages
state path: /Users/username/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/username/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.264686
using gpu buffer for window
startup time: 0.66492
git: ignoring working dir /Users/username
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin MarkdownPreview.markdown_preview
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
plugins loaded
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_cleanup.py", line 321, in <lambda>
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_cleanup.py", line 469, in finish
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/automatic_upgrader.py", line 67, in __init__
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/automatic_upgrader.py", line 106, in save_last_run
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/open_compat.py", line 22, in open_compat
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Library/Application Support/Sublime Text 3/Cache/Package Control/last_run.json'
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3211
  Package Control Version: 3.4.1
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 60, in make_package_list
    packages = self.manager.list_available_packages()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 694, in list_available_packages
    return self._list_available()[0]
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/providers/channel_provider.py", line 86, in fetch
    with downloader(self.channel, self.settings) as manager:
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 51, in downloader
    manager = _grab(url, settings)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 76, in _grab
    _managers[hostname].append(DownloadManager(settings))
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 184, in __init__
    self.settings['cache'] = HttpCache(cache_length)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/http_cache.py", line 18, in __init__
    os.mkdir(self.base_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Library/Application Support/Sublime Text 3/Cache/Package Control/http_cache'

**Comment by FichteFoll** [comment]
Your permissions seem to be messed up. Check the permissions of the paths mentioned in the tracebacks.

**Comment by RMcGhee** [comment]
Permissions for folders were fine, was able to resolve the issue by uninstalling and deleting all Application Support files, then reinstalling and copying back the Installed Packages and Packages folders.

**Comment by RMcGhee** [comment]
Problem resolved.
