### ISSUE TITLE
my package control is weird

### ISSUE THREAD

**Issue by ahmednadye** [wbond/package_control#1534]
hey please help 
i'm using windows 10 and i can't browse packages after i click package control:install package nothing happens this is the console
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/ahmed/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/ahmed/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/ahmed/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
unable to write startup cache to /C/Users/ahmed/AppData/Local/Sublime Text 3/Cache/Default/Startup.cache
pre session restore time: 0.157797
startup time: 0.212797
first paint time: 0.214797
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_cleanup.py", line 321, in <lambda>
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_cleanup.py", line 469, in finish
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/automatic_upgrader.py", line 67, in __init__
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/automatic_upgrader.py", line 106, in save_last_run
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/open_compat.py", line 22, in open_compat
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ahmed\\AppData\\Local\\Sublime Text 3\\Cache\\Package Control\\last_run.json'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/commands/install_package_command.py", line 45, in run
    self.package_list = self.make_package_list(['upgrade', 'downgrade', 'reinstall', 'pull', 'none'])
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_installer.py", line 60, in make_package_list
    packages = self.manager.list_available_packages()
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_manager.py", line 694, in list_available_packages
    return self._list_available()[0]
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_manager.py", line 554, in _list_available
    repositories = self.list_repositories()
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_manager.py", line 453, in list_repositories
    channel_repositories = provider.get_repositories()
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/providers/channel_provider.py", line 201, in get_repositories
    self.fetch()
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/providers/channel_provider.py", line 87, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/download_manager.py", line 351, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/downloaders/wininet_downloader.py", line 652, in download
    result = self.cache_result('get', url, general['status'], headers, result)
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/downloaders/caching_downloader.py", line 175, in cache_result
    cache.set(info_key, struct_json.encode('utf-8'))
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/http_cache.py", line 87, in set
    with open_compat(cache_file, 'wb') as f:
  File "C:\Users\ahmed\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/open_compat.py", line 22, in open_compat
    return open(path, mode, encoding=encoding, errors=errors)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ahmed\\AppData\\Local\\Sublime Text 3\\Cache\\Package Control\\http_cache\\01524fae79697630d0454ba3fabd9414.info'

**Comment by deathaxe** [comment]
> [Errno 13] Permission denied

It appears something is holding a lock on some files in ST's Cache directory (AntiVirus?) or permissions being set in a way that writing those files is prohabited.

Do the following steps solve the issue?

1. Close all instances of ST
2. Navigate to "C:\Users\ahmed\AppData\Local\Sublime Text 3\Cache\"
3. Remove "Package Control" folder
4. Restart ST

**Comment by ahmednadye** [comment]
Yesss!! thank you so much ❤️
