### ISSUE TITLE
Exception when migrating deps in four-point-oh branch

### ISSUE THREAD

**Issue by rwols** [wbond/package_control#1549]
The following exception occurs on startup.

```
Package Control: Error trying to migrate dependencies - [Errno 17] File exists: '/Users/raoulwols/Library/Application Support/Sublime Text 3/Lib/python33/yaml'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/Package Control/2_bootstrap.py", line 113, in _migrate_loaders
    plat_specific
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/dependency.py", line 94, in install
    shutil.copytree(source, os.path.join(dest_root, dname))
  File "./python3.3/shutil.py", line 301, in copytree
  File "./python3.3/os.py", line 262, in makedirs
FileExistsError: [Errno 17] File exists: '/Users/raoulwols/Library/Application Support/Sublime Text 3/Lib/python33/yaml'
```

**Comment by deathaxe** [comment]
Fixed
