### ISSUE TITLE
Package Control not working, not in ignored packages

### ISSUE THREAD

**Issue by brandonmcconnell** [wbond/package_control#1567]
I try to invoke Package Control the usual way Cmd+Shift+P and search for "Package Control" and nothing comes up. A console error shows there is a missing file. Where can I go to resolve these issues?

**Errors from console:**

```
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
AttributeError: 'module' object has no attribute 'events'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default'
```

**Full console output:**

```
startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages
state path: /Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.738631
using gpu buffer for window
using gpu buffer for window
startup time: 1.80165
git: tracking working dir /Users/brandonmcconnell/Sites/localhost/hci.com
Unable to open /private/var/folders/td/mxrd6_s10wxbsms09hmm3rq80000gn/T/fz3temp-2/v1.php
Unable to open /private/var/folders/td/mxrd6_s10wxbsms09hmm3rq80000gn/T/fz3temp-2/header.php
Unable to open /private/var/folders/td/mxrd6_s10wxbsms09hmm3rq80000gn/T/fz3temp-2/footer.php
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin CodeKit Commands.codekit
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin CSS Extended Completions.cache
reloading plugin CSS Extended Completions.commands
reloading plugin CSS Extended Completions.completions
reloading plugin CSS Extended Completions.css_style_completions
reloading plugin CSS Extended Completions.extended_css_completions
reloading plugin CSS Extended Completions.location
reloading plugin CSS Extended Completions.project
reloading plugin CSS Extended Completions.settings
reloading plugin CSS Extended Completions.style_parser
reloading plugin Emmet.emmet-plugin
reloading plugin LESS.less_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Traceback (most recent call last):
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 7, in <module>
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/2_bootstrap.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/bootstrap.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation_ctypes.py", line 21, in <module>
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 7, in <module>
ImportError: No module named 'Package Control.package_control.deps.oscrypto._osx._core_foundation_cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/Package Control.py", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/commands/advanced_install_package_command.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/trust_list.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_osx/_core_foundation_ctypes.py", line 21, in <module>
Package Control.package_control.deps.oscrypto.errors.LibraryNotFoundError: The library CoreFoundation could not be found
reloading plugin PHP Codebeautifier.phpcbf
reloading plugin Sass.sass_completions
reloading plugin SCSS Expander.__init__
reloading plugin SCSS Expander.scss_expander
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeTmpl.sublime-tmpl
reloading plugin Theme - Monokai Pro.Monokai Pro
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin WakaTime.WakaTime
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 51, in plugin_loaded
    package_control.events.install('SublimeLinter') or
AttributeError: 'module' object has no attribute 'events'
[WakaTime] [INFO] Initializing WakaTime plugin v9.1.2
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: You have the most recent PyV8 binary
using gpu buffer for window
Unable to open /Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 121, in on_activated_async
    CodeKit().handle_view_activated(view)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 85, in handle_view_activated
    self.activate_code_kit_project(view)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 65, in activate_code_kit_project
    if [i for i in config_files if i in os.listdir(path)]:
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 65, in <listcomp>
    if [i for i in config_files if i in os.listdir(path)]:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 121, in on_activated_async
    CodeKit().handle_view_activated(view)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 85, in handle_view_activated
    self.activate_code_kit_project(view)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 65, in activate_code_kit_project
    if [i for i in config_files if i in os.listdir(path)]:
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 65, in <listcomp>
    if [i for i in config_files if i in os.listdir(path)]:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 121, in on_activated_async
    CodeKit().handle_view_activated(view)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 85, in handle_view_activated
    self.activate_code_kit_project(view)
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 65, in activate_code_kit_project
    if [i for i in config_files if i in os.listdir(path)]:
  File "/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Installed Packages/CodeKit Commands.sublime-package/codekit.py", line 65, in <listcomp>
    if [i for i in config_files if i in os.listdir(path)]:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandonmcconnell/Library/Application Support/Sublime Text 3/Packages/Default'
```

**Comment by brandonmcconnell** [comment]
This appears to be related to the Big Sur bugs others experienced in this issue: #1475

Closing out this issue as a duplicate.
