### ISSUE TITLE
PC on master throws exception, while auto-upgrading

### ISSUE THREAD

**Issue by deathaxe** [wbond/package_control#1582]
Just after starting ST, the following traceback is printed.

```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 139, in run
    self.upgrade_packages()
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 269, in upgrade_packages
    self.package_renamer.rename_packages(self.installer)
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\package_renamer.py", line 36, in rename_packages
    installer.manager.list_available_packages()
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 696, in list_available_packages
    return self._list_available()[0]
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 556, in _list_available
    repositories = self.list_repositories()
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 455, in list_repositories
    channel_repositories = provider.get_repositories()
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\providers\channel_provider.py", line 203, in get_repositories
    self.fetch()
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\providers\channel_provider.py", line 89, in fetch
    channel_json = manager.fetch(self.channel, 'Error downloading channel.')
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\download_manager.py", line 351, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\downloaders\wininet_downloader.py", line 276, in download
    username, password = self.get_username_password()
TypeError: get_username_password() missing 1 required positional argument: 'url'

```

**Comment by rchl** [comment]
Would running CI on Windows catch this issue?

**Comment by deathaxe** [comment]
Probably yes, as wininet downloader is the primary choise.

**Comment by wbond** [comment]
The master branch now has fairly extensive CI coverage, leveraging off of some GitHub Actions work I did on some other Python packages recently.

https://github.com/wbond/package_control/runs/3339967761
