### ISSUE TITLE
OSError: The Trust Settings Record was corrupted. macOS Big Sur 11.5.1

### ISSUE THREAD

**Issue by jconnary** [wbond/package_control#1584]
Hello.

I'm getting the following error when trying to install packages with package control. I've tried uninstalling and re-installing several times without success. I've changed the channel in my user setting to use http to get Package Control to work at all, as it fails with https. I am not behind a proxy. I see that a similar issue was opened years ago for macOS 10.12, but nothing in that issue seemed to help my situation here. If you need any other info, then please ask. Thanks in advance for your help.

Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 4113
  Package Control Version: 3.4.1
Package Control: Download Debug
  URL: http://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Urllib HTTP Debug General
  Connecting to packagecontrol.io on port 80
Package Control: Urllib HTTP Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: bzip2,gzip,deflate
  Host: packagecontrol.io
  If-None-Match: "611d100b-5f4b8"
  If-Modified-Since: Wed, 18 Aug 2021 13:50:03 GMT
  Connection: Keep-Alive
  User-Agent: Package Control v3.4.1
Package Control: Urllib HTTP Debug Read
  HTTP/1.1 301 Moved Permanently
  Server: nginx
  Date: Wed, 18 Aug 2021 14:44:27 GMT
  Content-Type: text/html
  Content-Length: 178
  Connection: keep-alive
  Location: https://packagecontrol.io/channel_v3.json
  Strict-Transport-Security: max-age=15552000
Package Control: Caching http://packagecontrol.io/channel_v3.json in /Users/jeff/Library/Caches/Sublime Text/Cache/Package Control/http_cache/e1a9212887c875aa05f5ec63f0aa5bea
Package Control: Fixed URL from https://raw.github.com/darinmorrison/sublime-packages/master/packages.json to https://raw.githubusercontent.com/darinmorrison/sublime-packages/master/packages.json
Package Control: Fixed URL from https://raw.github.com/darinmorrison/sublime-packages/master/packages.json to https://raw.githubusercontent.com/darinmorrison/sublime-packages/master/packages.json
Package Control: Urllib HTTP Debug General
  Closing connection to packagecontrol.io on port 80 after 1 request
ignored packages updated to: ["0_package_control_loader", "LSP-bash"]
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 4113
  Package Control Version: 3.4.1
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Download Debug
  URL: https://codeload.github.com/sublimelsp/LSP-bash/zip/1.0.10
  Timeout: 30
  Resolved IP: 140.82.121.10
  Resolved IPv6: ::ffff:140.82.121.10
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system keychain
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_installer.py", line 225, in run
    self.result = self.manager.install_package(self.package)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 1115, in install_package
    package_bytes = manager.fetch(url, 'Error downloading package.')
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 351, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 117, in download
    self.setup_opener(url, timeout)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 317, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 31, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/ca_certs.py", line 164, in get_system_ca_bundle_path
    trust_list.get_path(ca_bundle_dir, hours_to_cache, cert_callback=cert_callback)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/trust_list.py", line 108, in get_path
    for cert, trust_oids, reject_oids in extract_from_system(cert_callback, True):
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/trust_list.py", line 54, in extract_from_system
    handle_sec_error(res)
  File "/Users/jeff/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/deps/oscrypto/_mac/_security.py", line 57, in handle_sec_error
    raise exception_class(output)
OSError: The Trust Settings Record was corrupted.

ignored packages updated to: ["0_package_control_loader"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

**Comment by deathaxe** [comment]
related to #1154
