### ISSUE TITLE
[four-point-oh] KeyError in "Satisfy Libraries..."

### ISSUE THREAD

**Issue by deathaxe** [wbond/package_control#1587]
```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\commands\satisfy_libraries_command.py", line 46, in run
    if not self.manager.install_libraries(required_libraries, fail_early=False):
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\package_manager.py", line 1668, in install_libraries
    library_write('is not currently installed; installing...')
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\package_manager.py", line 1654, in library_write
    msg = msg.format(
KeyError: 'library_name'
```

**Comment by deathaxe** [comment]
Seems to work with latest commits.
