### ISSUE TITLE
[four-point-oh]

### ISSUE THREAD

**Issue by deathaxe** [wbond/package_control#1588]
The following traceback is printed while auto-update tries to update `requests` library.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 120, in run
    self.install_missing()
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\automatic_upgrader.py", line 160, in install_missing
    if self.installer.manager.install_library(library):
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\package_manager.py", line 1107, in install_library
    success = self._extract_zip(
  File "C:\Apps\Sublime Text 40xx\Data\Packages\Package Control\package_control\package_manager.py", line 999, in _extract_zip
    os.makedirs(dest, exist_ok=True)
  File "./python3.8/os.py", line 213, in makedirs
  File "./python3.8/os.py", line 223, in makedirs
FileNotFoundError: [WinError 206] Der Dateiname oder die Erweiterung ist zu lang: 'C:\\Users\\DeathAxe\\AppData\\Local\\Temp\\tmp5ly__usr\\requests\\all\\all\\all\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests\\all\\requests'
```

**Comment by deathaxe** [comment]
Seems fixed.
