### ISSUE TITLE
[four-point-oh] Type conflict in package_manager.find_required_libraries()

### ISSUE THREAD

**Issue by deathaxe** [wbond/package_control#1593]
I see folowing traceback when starting ST with 3d4b9e7c7822555a99425611e143b0906cd18e94.

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\package_cleanup.py", line 107, in run
    required_libraries = self.manager.find_required_libraries()
  File "C:\Apps\Sublime Text\Data\Packages\Package Control\package_control\package_manager.py", line 775, in find_required_libraries
    output |= self.get_libraries(package)
TypeError: unsupported operand type(s) for |=: 'set' and 'list'
```

**Comment by rwols** [comment]
Same here. With all these silly type bugs, it might be time to start using LSP-pyright :)

**Comment by deathaxe** [comment]
I should open a PR with some of my fixes.
