### ISSUE TITLE
'ValidatingHTTPSConnection' object has no attribute '_set_hostport'

### ISSUE THREAD

**Issue by bokix** [wbond/package_control#1650]
download from :[Package Control 4.0.0-beta5](https://github.com/wbond/package_control/releases/tag/4.0.0-beta5)

**console log:**

startup, version: 4150 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/bokix/Library/Application Support/Sublime Text/Packages
state path: /Users/bokix/Library/Application Support/Sublime Text/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/bokix/Library/Application Support/Sublime Text/Installed Packages
ignored_packages: []
pre session restore time: 0.333266
OpenGL Context Information:
  GL API Version: 4.1 INTEL-20.6.4
  GLSL Version: 4.10
  Vendor: Intel Inc.
  Renderer: Intel(R) UHD Graphics 630
startup time: 0.435011
first paint time: 0.573753
environment variables loaded using: /bin/zsh -l
reloading python 3.3 plugin View In Browser.ViewInBrowserCommand
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin Package Control.plugin
plugins loaded
ignored packages updated to: ["View In Browser"]
unloading python 3.3 plugin View In Browser.ViewInBrowserCommand
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The package "View In Browser" has been removed
ignored packages updated to: []
reloading settings Packages/User/Package Control.sublime-settings
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_cleanup.py", line 71, in run
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_cleanup.py", line 487, in remove_orphaned_packages
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_tasks.py", line 291, in remove_packages
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 1978, in remove_package
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/package_manager.py", line 2312, in record_usage
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 78, in http_get
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/download_manager.py", line 460, in fetch
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/downloaders/urllib_downloader.py", line 116, in download
  File "./python3.8/urllib/request.py", line 525, in open
  File "./python3.8/urllib/request.py", line 542, in _open
  File "./python3.8/urllib/request.py", line 502, in _call_chain
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/http/validating_https_handler.py", line 33, in https_open
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/http/persistent_handler.py", line 74, in do_open
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/http/debuggable_http_connection.py", line 69, in request
  File "./python3.8/http/client.py", line 1256, in request
  File "./python3.8/http/client.py", line 1302, in _send_request
  File "./python3.8/http/client.py", line 1251, in endheaders
  File "./python3.8/http/client.py", line 1011, in _send_output
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/http/debuggable_http_connection.py", line 47, in send
  File "./python3.8/http/client.py", line 951, in send
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/http/validating_https_connection.py", line 284, in connect
  File "/Users/bokix/Library/Application Support/Sublime Text/Installed Packages/Package Control.sublime-package/package_control/http/validating_https_connection.py", line 97, in _tunnel
AttributeError: 'ValidatingHTTPSConnection' object has no attribute '_set_hostport'
reloading settings Packages/User/Preferences.sublime-settings

**Comment by deathaxe** [comment]
Should be fixed in [4.0.0-beta6](https://github.com/wbond/package_control/releases/tag/4.0.0-beta6).
