### ISSUE TITLE
ST3: (3009) No module named 'package_control'

### ISSUE THREAD

**Issue by ashemedai** [wbond/package_control#312]
Using build 3009 I installed the Package Control.sublime-package into the Sublime Text 3 Installed Packages directory. After restarting Sublime Text 3 I get the following in console:

``` python
reloading plugin Package Control.Package Control
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "C:\Users\asmodai\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\Package Control.py", line 7, in <module>
ImportError: No module named 'package_control'
```

**Comment by jasalazar** [comment]
Same issue on 3059 running Ubuntu 14.04.2
