### ISSUE TITLE
i cant install package from install control ? any solution

### ISSUE THREAD

**Issue by ardani** [wbond/package_control#671]
first i am sorry may be this question is not good, but package control is usefull for me,
i have i problem with install package .
this console message

```
Exception in thread Thread-34:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\package_control\downloaders\background_downloader.py", line 61, in run
  File ".\package_control\providers\repository_provider.py", line 77, in prefetch
  File ".\package_control\providers\repository_provider.py", line 271, in get_packages
AttributeError: 'unicode' object has no attribute 'get'

Exception in thread Thread-32:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\package_control\commands\install_package_command.py", line 43, in run
  File ".\package_control\package_installer.py", line 54, in make_package_list
  File ".\package_control\package_manager.py", line 260, in list_available_packages
  File ".\package_control\downloaders\background_downloader.py", line 52, in get_provider
KeyError: u'http://sublime.wbond.net/repositories.json'
```

i am sorry my english not good 
thanks

**Comment by tinypuppet** [comment]
@idiotize Thank you!
