### ISSUE TITLE
error downloading channel.json / No packages available

### ISSUE THREAD

**Issue by weems** [wbond/package_control#723]
## Stacktrace

```
Package Control: Error submitting usage information. URL error  downloading https://sublime.wbond.net/submit?package_control_version=2.0.0&sublime_platform=osx&package=Package+Control&sublime_version=2221&version=2.0.0&operation=install.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1181, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1156, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
reloading /Users/michaelweems/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
Package Control: Error downloading channel. URL error  downloading https://sublime.wbond.net/channel.json.
Package Control: Error downloading channel. URL error  downloading https://sublime.wbond.net/channel.json.
Package Control: No updated packages
```

**Comment by clfeng** [comment]
my issue is that 
Package Control: Error downloading channel. HTTP error 404 downloading https://dn-52cik.qbox.me/channel_v3.json.
anyone can hlep me to sovle the issue

**Comment by FichteFoll** [comment]
I wish people would stop necroing old and solved issues with completely irrelevant different problems on [multiple occasions](https://github.com/wbond/package_control/issues/814#issuecomment-281360687).

But since I clicked on this issue anyway, I might as well tell you how to fix it: Remove the `"channels"` key-value pair from your Package Control user settings.

**Comment by clfeng** [comment]
According to your method,I have solved my issue, thank you so much and sorry to disturb you with the old issues.
