### ISSUE TITLE
PC 3.0.0 unable to install packages.

### ISSUE THREAD

**Issue by Adarma** [wbond/package_control#826]
After manually installing 3.0.0 on clean portable SublimeText 3065, Windows XP x86 I get the following log on startup:
```
DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)/sublime_text.exe
working dir: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)
packages path: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)/Data/Packages
state path: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)/Data/Local
hardware concurrency: 4
zip path: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)/Packages
zip path: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)/Data/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 4 orphaned files: 0 total files: 169 cache hits: 165
pre session restore time: 0.171269
startup time: 0.218269
first paint time: 0.218269
launching: /D/!PORTABLE!/Sublime Text Build 3065 (TEST)/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
loaded 837 snippets
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 1 missing dependencies
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "package_control.download_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.wininet_downloader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 377, in download
Package Control.package_control.downloaders.win_downloader_exception.WinDownloaderException: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 111, in run
  File "package_control.automatic_upgrader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 162, in install_missing
  File "package_control.package_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 756, in install_package
  File "package_control.download_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 308, in fetch
  File "package_control.download_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.urllib_downloader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 102, in download
  File "package_control.downloaders.urllib_downloader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 275, in setup_opener
  File "package_control.ca_certs in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 50, in get_ca_bundle_path
  File "package_control.ca_certs in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 139, in get_system_ca_bundle_path
  File "package_control.ca_certs in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 394, in _win_create_ca_bundle
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 472, in parse
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 452, in load
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 452, in load
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 447, in load
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 95, in read
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 174, in _read_value
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 245, in _decode_integer
TypeError: 'bytes' object does not support item assignment
```

Then attempting to install `SublimeLinter` via package control I get:
```
ignored packages updated to: [Vintage, SublimeLinter]
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/SublimeLinter/SublimeLinter3/zip/3.4.29.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "package_control.download_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.wininet_downloader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 377, in download
Package Control.package_control.downloaders.win_downloader_exception.WinDownloaderException: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/SublimeLinter/SublimeLinter3/zip/3.4.29.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.package_installer in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 212, in run
  File "package_control.package_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 756, in install_package
  File "package_control.download_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 308, in fetch
  File "package_control.download_manager in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.urllib_downloader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 102, in download
  File "package_control.downloaders.urllib_downloader in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 275, in setup_opener
  File "package_control.ca_certs in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 50, in get_ca_bundle_path
  File "package_control.ca_certs in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 139, in get_system_ca_bundle_path
  File "package_control.ca_certs in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 394, in _win_create_ca_bundle
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 472, in parse
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 452, in load
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 452, in load
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 447, in load
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 95, in read
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 174, in _read_value
  File "package_control.http.x509 in D:\!PORTABLE!\Sublime Text Build 3065 (TEST)\Data\Installed Packages\Package Control.sublime-package", line 245, in _decode_integer
TypeError: 'bytes' object does not support item assignment

ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
```

SublimeLinter is not installed.

I have never been able to install Package Control with `Simple` Installation from my work computer. I have always had to do the `Manual` Installation.

I wondered it the IT guys had changed something over the Christmas break, so I manually installed PC2.0.0 from the GitHub zip download into a clean portable SublimeText 3065. I got the upgraded to 3.0.0 message, so that seems to work. I am then still unable to install packages. I guess because I am back to 3.0.0. I can't run the code for `Windows Sublime Text 3 Users` because it does not work from this network. If I manually install it, am am back to the original situation.

**Comment by wbond** [comment]
Try following the directions for error 12029 at https://packagecontrol.io/docs/troubleshooting#Windows_Errors_12029_and_12057.

My guess is that your machine currently isn't accepting TLS 1.x connections. PC 3.0 uses packagecontrol.io instead of sublime.wbond.net. packagecontrol.io has a much more secure cipher suite that disables SSLv3 since it is broken.

**Comment by wbond** [comment]
Any luck?

**Comment by Adarma** [comment]
Sorry not to check faster.
I tried the directions, but it didn't resolve it.
If it is a Win XP thing, then I don't expect you to fix it.
Hopefully the IT guys will upgrade the machines at some point...

**Comment by wbond** [comment]
In ca05ef54b0c1c8ef9155468f4dc69a07cad9f4aa I fixed the TypeError, which may make it possible for you to use the fallback urllib downloader.

Version 3.0.1 should be released in the next day or two with this fix.

**Comment by ragamufin** [comment]
I added the fix you mentioned above and it resolved my issue with errno 12157. Thanks!

**Comment by Adarma** [comment]
I have tried with 3.0.1-beta2.
It still fails with:

```
...
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
loaded 837 snippets
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
Package Control: Error downloading package. URL error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond downloading https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0.
error: Package Control

Unable to download bz2. Please view the console for more details.
Package Control: Skipping automatic upgrade, last run at 2015-01-20 15:45:34, next run at 2015-01-20 16:45:34 or after
error: Package Control

1 missing dependency were just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

I get two popup errors with the same text as in the log, indication a download failure, and also an installation success! I guess the second error with the restart message is wrong.

"0_package_control_loader.sublime-package" appears in the "Installed Packages" folder, but I assume that is generated by code and not downloaded.

If I try to download the file "https://codeload.github.com/codexns/sublime-bz2/zip/1.0.0" from a browser it works. I have "Automatically detect settings" enabled for LAN proxy settings.

**Comment by wbond** [comment]
@Adarma Package Control can not autodetect proxy settings for the Urllib downloader. You'll need to set [`https_proxy`](https://packagecontrol.io/docs/settings#setting-https_proxy), [`proxy_username`](https://packagecontrol.io/docs/settings#setting-proxy_username) and [`proxy_password`](https://packagecontrol.io/docs/settings#setting-proxy_password).

An alternative is you can try following the directions for error 12029 at https://packagecontrol.io/docs/troubleshooting#Windows_Errors_12029_and_12057.

**Comment by wbond** [comment]
Sorry, just noticed that I had recommended the 12029 fix earlier in the thread.

**Comment by Adarma** [comment]
Is `https_proxy`used on windows? The comment in the settings file says it is not.
Anyway, I tried with the settings configured and still no luck.
If `WinINet` is used, shouldn't it be possible to download everything that InternetExplorer can?

**Comment by wbond** [comment]
@Adarma It should be possibly, but something it broken in Windows, hence the error `Secure channel error, server not providing SSL (errno 12157)` that is coming out of WinINet. It sounds to me like something on your machine or network is messing with the connection.

The `https_proxy` is now used on Windows when falling back to the urllib downloader. The urllib downloader for Windows is a new fallback for when WinINet decides it is going out to lunch. I will have to fix the comment.

What is your debug log with `https_proxy` set?

**Comment by Adarma** [comment]
Well, I went to get you the debug log, and everything worked! Maybe it was a network issue which has now been resolved.

It only works with the beta which resolved the TypeError.

I guess this can be closed now, but maybe you want to update the settings file comment to say the proxy is used on windows when WinINet fails.

Thanks

**Comment by dominiklenne** [comment]
Just as a remark, XP does't support TLS 1.1 or 1.2.

**Comment by wbond** [comment]
@dominiklenne Thanks for pointing that out. At this point the server supports TLS 1.x, so XP should select 1.0 as long as your are running SP3.

**Comment by wbond** [comment]
Well, this seems to be resolved. I'm closing. If anyone has issues with 3.0.1, please open a new issue with a debug log.
