### ISSUE TITLE
Can not remove disabled package

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#836]
```
Traceback (most recent call last):
  File "package_control.commands.remove_package_command in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 76, in unignore_package
  File "package_control.package_disabler in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 145, in reenable_package
  File "package_control.events in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 69, in clear
  File "package_control.events in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 64, in do_clear
KeyError: 'RequestsTest'
```

Some bug with the events code if the package was not previously disabled in the "remove_package" procedure. Should be an easy fix.

**Comment by FichteFoll** [comment]
Just found that this is a duplicate: #822
