### ISSUE TITLE
Reporting package is installed but doenst load

### ISSUE THREAD

**Issue by diego898** [wbond/package_control#852]
Hello,

I am having a strange issue when I try and instal "Google Spell Check" plugin. I search for it, install it and package control reports that it was installed correctly. I then try to bring it up from the command pallete and I cant. I then list installed packages and it shows up, but when I restart sublime with debug set to true, I get the following: 

```
DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Installed Packages
found 13 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 13 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 0 total files: 315 cache hits: 314
pre session restore time: 0.114618
Loading dictionary Packages/Language - English/en_US.dic
startup time: 0.164618
first paint time: 0.165618
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
loaded 902 snippets
reloading plugin Alignment.Alignment
reloading plugin AutoWrap.autowrap
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin FileDiffs.file_diffs
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin LaTeXing.LaTeXing
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Sublime Files.sublime_files
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin WordCount.WordCount
reloading plugin Wrap Plus.wrap_plus
reloading plugin PlainTasks.PlainTasks
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: generate_color_scheme: Preferences.sublime-settings invalid, aborting 
found 13 files for base name Main.sublime-menu
Package Control: Unable to find file package-metadata.json in the package folder for HTML
Package Control: Unable to find a sublime-package file for HTML
Package Control: Unable to find file package-metadata.json in the package HTML
Package Control: Unable to find file package-metadata.json in the package folder for HTML
Package Control: Unable to find a sublime-package file for HTML
Package Control: Unable to find file package-metadata.json in the package HTML
Package Control: Unable to find file package-metadata.json in the package folder for Rails
Package Control: Unable to find a sublime-package file for Rails
Package Control: Unable to find file package-metadata.json in the package Rails
Package Control: Unable to find file package-metadata.json in the package folder for Rails
Package Control: Unable to find a sublime-package file for Rails
Package Control: Unable to find file package-metadata.json in the package Rails
Package Control: Skipping automatic upgrade, last run at 2015-01-23 17:25:52, next run at 2015-01-23 18:25:52 or after
SublimeLinter: annotations activated: <builtin> 
```

For which, `Google` does not show up. I have tried removing/reinstalling/restarting several times and I still get the issue. 

Also, my `Package Control.sublime-settings` file, does list `Google Spell Check`.

**Comment by wbond** [comment]
Please provide a debug log that includes you installing the package.

**Comment by diego898** [comment]
Hello,

Below are two logs 

Here is the log after a restart and *installation*.
```
DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Installed Packages
found 13 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 13 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 315 cache hits: 313
pre session restore time: 0.108091
Loading dictionary Packages/Language - English/en_US.dic
startup time: 0.168091
first paint time: 0.168091
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Alignment.Alignment
reloading plugin AutoWrap.autowrap
reloading plugin BracketHighlighter.bh_core
loaded 902 snippets
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin FileDiffs.file_diffs
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin LaTeXing.LaTeXing
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Sublime Files.sublime_files
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin WordCount.WordCount
reloading plugin Wrap Plus.wrap_plus
reloading plugin PlainTasks.PlainTasks
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: generate_color_scheme: Preferences.sublime-settings invalid, aborting 
found 13 files for base name Main.sublime-menu
Package Control: Unable to find file package-metadata.json in the package folder for HTML
Package Control: Unable to find a sublime-package file for HTML
Package Control: Unable to find file package-metadata.json in the package HTML
Package Control: Unable to find file package-metadata.json in the package folder for HTML
Package Control: Unable to find a sublime-package file for HTML
Package Control: Unable to find file package-metadata.json in the package HTML
Package Control: Unable to find file package-metadata.json in the package folder for Rails
Package Control: Unable to find a sublime-package file for Rails
Package Control: Unable to find file package-metadata.json in the package Rails
Package Control: Unable to find file package-metadata.json in the package folder for Rails
Package Control: Unable to find a sublime-package file for Rails
Package Control: Unable to find file package-metadata.json in the package Rails
Package Control: Skipping automatic upgrade, last run at 2015-01-24 11:33:41, next run at 2015-01-24 12:33:41 or after
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: annotations activated: <builtin> 
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Tue, 16 Dec 2014 16:00:00 GMT
    expire date: Thu, 29 Oct 2015 16:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  Accept-Encoding: gzip,deflate
  If-Modified-Since: Sat, 24 Jan 2015 19:30:03 GMT
  User-Agent: Package Control v3.0.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Sat, 24 Jan 2015 19:35:34 GMT
  Last-Modified: Sat, 24 Jan 2015 19:30:03 GMT
  Connection: keep-alive
  ETag: "54c3f2bb-1d2dde"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from C:\Users\diego\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Unable to find a sublime-package file for Google Spell Check
Package Control: Unable to find file package-metadata.json in the package Google Spell Check
Package Control: Download Debug
  URL: https://codeload.github.com/noahcoad/google-spell-check/zip/st3
  Resolved IP: 192.30.252.147
  Timeout: 30
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Cobalt2.sublime-theme
SublimeLinter: generate_color_scheme: Preferences.sublime-settings invalid, aborting 
theme loaded
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, California, San Francisco, "GitHub, Inc.", *.github.com
    issuer: US, DigiCert Inc, www.digicert.com, DigiCert SHA2 High Assurance Server CA
    common name: *.github.com
    issue date: Mon, 07 Apr 2014 17:00:00 GMT
    expire date: Wed, 12 Apr 2017 05:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /noahcoad/google-spell-check/zip/st3 HTTP/1.1
  Accept-Encoding: gzip,deflate
  User-Agent: Package Control v3.0.0
  Host: codeload.github.com
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Content-Length: 93197
  Access-Control-Allow-Origin: https://render.githubusercontent.com
  Content-Security-Policy: default-src 'none'
  X-XSS-Protection: 1; mode=block
  X-Frame-Options: deny
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000
  Vary: Authorization,Accept-Encoding
  ETag: "c402ec2fd56ae309351d479b5ef2682e515db701"
  Content-Type: application/zip
  Content-Disposition: attachment; filename=google-spell-check-st3.zip
  Date: Sat, 24 Jan 2015 19:35:38 GMT
Package Control: Skipping cache since the response is a zip file
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package=Google+Spell+Check&version=2014.08.11.19.11.27&sublime_platform=windows&operation=install&package_control_version=3.0.0&sublime_version=3065
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #1
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug Write
  GET /submit?package=Google+Spell+Check&version=2014.08.11.19.11.27&sublime_platform=windows&operation=install&package_control_version=3.0.0&sublime_version=3065 HTTP/1.1
  Accept-Encoding: gzip,deflate
  User-Agent: Package Control v3.0.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sat, 24 Jan 2015 19:35:39 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.1.1
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
reloading Packages/User/Package Control.sublime-settings
Package Control: WinINet HTTPS Debug General
  Closing connection to codeload.github.com on port 443 after 1 request
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests
```


Here is the log after a restart and *uninstall*:

```
DPI scale: 1
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/diego/AppData/Roaming/Sublime Text 3/Installed Packages
found 13 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 13 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Cobalt2.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 315 cache hits: 313
pre session restore time: 0.110786
Loading dictionary Packages/Language - English/en_US.dic
startup time: 0.179786
first paint time: 0.180786
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Alignment.Alignment
reloading plugin AutoWrap.autowrap
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
loaded 902 snippets
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin FileDiffs.file_diffs
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin LaTeXing.LaTeXing
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Sublime Files.sublime_files
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin WordCount.WordCount
reloading plugin Wrap Plus.wrap_plus
reloading plugin PlainTasks.PlainTasks
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: generate_color_scheme: Preferences.sublime-settings invalid, aborting 
found 13 files for base name Main.sublime-menu
Package Control: Unable to find file package-metadata.json in the package folder for HTML
Package Control: Unable to find a sublime-package file for HTML
Package Control: Unable to find file package-metadata.json in the package HTML
Package Control: Unable to find file package-metadata.json in the package folder for HTML
Package Control: Unable to find a sublime-package file for HTML
Package Control: Unable to find file package-metadata.json in the package HTML
Package Control: Unable to find file package-metadata.json in the package folder for Rails
Package Control: Unable to find a sublime-package file for Rails
Package Control: Unable to find file package-metadata.json in the package Rails
Package Control: Unable to find file package-metadata.json in the package folder for Rails
Package Control: Unable to find a sublime-package file for Rails
Package Control: Unable to find file package-metadata.json in the package Rails
SublimeLinter: annotations activated: <builtin> 
Package Control: Skipping automatic upgrade, last run at 2015-01-24 11:33:41, next run at 2015-01-24 12:33:41 or after
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Cobalt2.sublime-theme
SublimeLinter: generate_color_scheme: Preferences.sublime-settings invalid, aborting 
theme loaded
Package Control: Download Debug
  URL: https://packagecontrol.io/submit?package_control_version=3.0.0&sublime_platform=windows&operation=remove&version=2014.08.11.19.11.27&package=Google+Spell+Check&sublime_version=3065
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Tue, 16 Dec 2014 16:00:00 GMT
    expire date: Thu, 29 Oct 2015 16:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /submit?package_control_version=3.0.0&sublime_platform=windows&operation=remove&version=2014.08.11.19.11.27&package=Google+Spell+Check&sublime_version=3065 HTTP/1.1
  Accept-Encoding: gzip,deflate
  User-Agent: Package Control v3.0.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Sat, 24 Jan 2015 19:37:18 GMT
  Content-Type: application/json
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-App-Version: 1.1.1
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
reloading Packages/User/Package Control.sublime-settings
Traceback (most recent call last):
  File "package_control.commands.remove_package_command in C:\Users\diego\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 76, in unignore_package
  File "package_control.package_disabler in C:\Users\diego\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 145, in reenable_package
  File "package_control.events in C:\Users\diego\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 69, in clear
  File "package_control.events in C:\Users\diego\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 64, in do_clear
KeyError: 'Google Spell Check'

```

**Comment by diego898** [comment]
Is that what you need?

**Comment by FichteFoll** [comment]
It seems like the package has been ignored accidentally (probably due to a PC bug) and another PC bug that has been fixed on `master` prevents the package from being enabled again on re-installation.

Check the setting `ignored_packages` in your user settings and remove the package from there.

**Comment by diego898** [comment]
hm. I have no idea how that got there, but it was being ignored. Removing that fixed it. Thanks for the help!
