### ISSUE TITLE
Packages are loading too quickly when installed as previously missing

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#855]
Because packages are not disabled during installation when they were missing before, they are loaded before their dependencies have been installed/loaded.

This is probably an ST2-only issue since ST needs some time to detect file changes to the loader package and for some reason seems to always load the package file earlier (in ST3 the loader code is run synchronously).

Similar issue to https://github.com/wbond/package_control/pull/845#issuecomment-70235019.

```
Package Control: Installing 1 missing package
Package Control: The dependency requests is not currently installed; installing
Package Control: The dependency requests has successfully been installed or updated
Reloading plugin C:\tools\Sublime Text 2\Data\Packages\RequestsTest\just_a_test.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\just_a_test.py", line 1, in <module>
    import requests
ImportError: No module named requests
Reloading plugin C:\tools\Sublime Text 2\Data\Packages\0_package_control_loader\50-requests.py
Package Control: Installed missing package RequestsTest
```

Note that it works when installing normally. Console log for that:
```
ignored packages updated to: [SublimeOnSaveBuild, Vintage, Markdown, WakaTime, RequestsTest]
[...]
Package Control: The dependency requests is not currently installed; installing
Package Control: The dependency requests has successfully been installed or updated
Reloading plugin C:\tools\Sublime Text 2\Data\Packages\0_package_control_loader\50-requests.py
reloading /C/tools/Sublime Text 2/Data/Packages/User/Package Control.sublime-settings
ignored packages updated to: [Vintage, SublimeOnSaveBuild, Markdown, WakaTime]
[...]
Reloading plugin C:\tools\Sublime Text 2\Data\Packages\RequestsTest\just_a_test.py
```

**Comment by wbond** [comment]
Should be fixed by 1380e014d542e98cebefc0a2818cef1d260d2e8e
