### ISSUE TITLE
Windows 7 - Connection issues behind corporate firewall

### ISSUE THREAD

**Issue by KyleRoss** [wbond/package_control#856]
Since the newest version of the package control was released, I've moved farther along in the task of getting it to work behind our corporate firewall (mostly because winINet doesn't work correctly since we are using a `proxy.pac` script). Now that it's falling back to `urllib` to make the connection, it can now connect to HTTP urls when `user_agent` is set to its default value. HTTPS connections though, do not connect and return the famous `errno 12029` error. 

For a test, I changed the `user_agent` to the same that is used by Chrome and it seems to be what it needs to connect through the proxy. I believe that uncommon user agents are blocked. The biggest issue now is that it is requiring NTLM authentication in which is not provided in `urllib` as far as I know. Would it be possible to add support for NTLM into the package control for `urllib`?

I've tried everything from proxy settings to providing my corporate login credentials with and without the domain and followed the troubleshooting guides.

```
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3065
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: http://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading http://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: http://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: proxy.mycompany.com:8080
  https_proxy: proxy.mycompany.com:8080
  proxy_username: 
  proxy_password: 
Package Control: Urllib HTTP Debug General
  Connecting to proxy.mycompany.com on port 8080
Package Control: Urllib HTTP Debug Write
  GET http://packagecontrol.io/channel_v3.json HTTP/1.1
  If-Modified-Since: Wed, 28 Jan 2015 17:10:03 GMT
  Host: packagecontrol.io
  User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36
  Connection: Keep-Alive
  Accept-Encoding: gzip,deflate
Package Control: Urllib HTTP Debug Read
  HTTP/1.1 407 Proxy Authentication Required
  Proxy-Authenticate: NTLM
  Proxy-Authenticate: NTLM
  Cache-Control: no-cache
  Pragma: no-cache
  Content-Type: text/html; charset=utf-8
  Proxy-Connection: close
  Set-Cookie: BCSI-CS-5c81991dbe324bf0=2; Path=/
  Connection: close
  Content-Length: 2414
Package Control: Urllib HTTP Debug General
  Closing connection to proxy.mycompany.com on port 8080 after 1 request
Exception in thread Thread-3:
Traceback (most recent call last):
  File "package_control.download_manager in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 377, in download
Package Control.package_control.downloaders.win_downloader_exception.WinDownloaderException: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading http://packagecontrol.io/channel_v3.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 111, in run
  File "package_control.automatic_upgrader in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 137, in install_missing
  File "package_control.package_manager in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 343, in list_available_packages
  File "package_control.package_manager in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 271, in list_repositories
  File "package_control.providers.channel_provider in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 189, in get_repositories
  File "package_control.providers.channel_provider in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 86, in fetch
  File "package_control.download_manager in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 308, in fetch
  File "package_control.download_manager in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.urllib_downloader in C:\Users\u187746\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 123, in download
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 507, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1157, in http_error_407
  File "./urllib/request.py", line 1031, in http_error_auth_reqed
ValueError: AbstractDigestAuthHandler does not support the following scheme: 'NTLM'
```

That is with the following settings:

``` json
{
    "debug": true,
    "user_agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36",
    "http_proxy": "proxy.mycompany.com:8080",
    "https_proxy": "proxy.mycompany.com:8080",

    "channels": [
        "http://packagecontrol.io/channel_v3.json"
    ]
}
```

**Comment by pomeh** [comment]
I'm no Package Control nor proxy expert, but did you tried with the default package control config ? Currently, I'm using a Windows 7 machine configured with a pac proxy file behind a corporate proxy file and which requires authentication and package control works likes a charm :) It worth try it :)

**Comment by FichteFoll** [comment]
The main problem why the default config would not work seems to be this:

> winINet doesn't work correctly since we are using a proxy.pac script

Since the default config uses wininit and that reads proxy settings for your internet options, your company probably set their proxy information there correctly.

**Comment by wbond** [comment]
Currently the NTLM authentication scheme for proxies is not supported. It used to be, but there were lots of bugs, and no one was able to give me access to a machine to debug with. So I gave up with Package Control 2.0 and added WinINet.

If you can give me access to a machine where I can work with an NTLM-based proxy, I'd be happy to try and get it working. Otherwise, if you can provide a patch that adds support, I'd be willing to review it.

**Comment by omgaz** [comment]
As of 3.1 proxy support has been added :+1:

**Comment by MrEfrem** [comment]
Via Digest proxy

```
Package Control: Not running package cleanup since bootstrapping is not yet complete
Package Control: Downloading bootstrapped dependency ssl-linux
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "package_control.bootstrap in /home/eav/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 109, in bootstrap_dependency
  File "package_control.download_manager in /home/eav/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
  File "package_control.downloaders.urllib_downloader in /home/eav/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 123, in download
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 507, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 981, in http_error_407
  File "./urllib/request.py", line 931, in http_error_auth_reqed
ValueError: AbstractBasicAuthHandler does not support the following scheme: 'Digest'
```

**Comment by MrEfrem** [comment]
Package Control.sublime-settings:
```
{
	"http_proxy": "http://proxy.my.ru:3128",
	"https_proxy": "http://proxy.my.ru:3128",
	"proxy_password": "user",
	"proxy_username": "pwd"
}

```

**Comment by deathaxe** [comment]
Package Control 3.4 uses wininet downloader by default. This downloader automatically uses system settings for proxies and CA. This should fix related issues on Windows.
