### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)

### ISSUE THREAD

**Issue by junkiemonkey** [wbond/package_control#861]
```
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 2221
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Exception in thread Thread-6:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\commands\install_package_command.py", line 43, in run
    'reinstall', 'pull', 'none'])
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\package_installer.py", line 61, in make_package_list
    packages = self.manager.list_available_packages()
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\package_manager.py", line 343, in list_available_packages
    repositories = self.list_repositories()
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\package_manager.py", line 271, in list_repositories
    channel_repositories = provider.get_repositories()
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\providers\channel_provider.py", line 189, in get_repositories
    self.fetch()
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\providers\channel_provider.py", line 86, in fetch
    'Error downloading channel.')
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\download_manager.py", line 264, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "C:\Users\Playloud\AppData\Roaming\SUBLIM~1\Packages\PACKAG~1\package_control\downloaders\wininet_downloader.py", line 513, in download
    if str(e).find('timed out') != -1:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)

Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 0 requests
```

**Comment by wbond** [comment]
Should be fixed by f1d40f6b0183cdc407321bfdd461ad0aad1cc3b0.
