### ISSUE TITLE
Error generating new CA bundle and OSError

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [wbond/package_control#862]
Getting several errors from PackageControl -- the HTTPS connect error is a  known issue, though I've not found a workaround. But it is the **other errors** that I'm reporting here:

* Exception while generating new certificates
* Exception in exception handler (an OSError)

This is on a Win8.1 system. Here's the debug log:

```
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3067
  Package Control Version: 3.0.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system certificate store
Package Control: Exported certificate "Microsoft Root Certificate Authority"
Package Control: Skipping certificate "Thawte Timestamping CA" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Skipping certificate "Microsoft Root Authority" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Exported certificate "Microsoft Root Certificate Authority 2011"
Package Control: Skipping certificate "Microsoft Authenticode(tm) Root Authority" since it is no longer valid
Exception in thread Thread-3:
Traceback (most recent call last):
  File "package_control.download_manager in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 377, in download
Package Control.package_control.downloaders.win_downloader_exception.WinDownloaderException: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 111, in run
  File "package_control.automatic_upgrader in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 137, in install_missing
  File "package_control.package_manager in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 343, in list_available_packages
  File "package_control.package_manager in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 271, in list_repositories
  File "package_control.providers.channel_provider in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 189, in get_repositories
  File "package_control.providers.channel_provider in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 86, in fetch
  File "package_control.download_manager in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 308, in fetch
  File "package_control.download_manager in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.urllib_downloader in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 102, in download
  File "package_control.downloaders.urllib_downloader in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 275, in setup_opener
  File "package_control.ca_certs in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 50, in get_ca_bundle_path
  File "package_control.ca_certs in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 139, in get_system_ca_bundle_path
  File "package_control.ca_certs in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 376, in _win_create_ca_bundle
  File "package_control.ca_certs in C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 543, in convert_filetime_to_datetime
OSError: [Errno 22] Invalid argument
```

**Comment by wbond** [comment]
The error 12029 has a fix that tends to work at https://packagecontrol.io/docs/troubleshooting#Windows_Errors_12029_and_12057. For some reason something on your machine is blocking the connection.

As for the certificate export error, I added a workaround in 26b13dc4b81c32bcb10a71d309d6a546eed11420. If you could post your debug log after running that version, I'd be curious to see what filetime is overflowing the datetime module.

**Comment by wbond** [comment]
You should be able to upgrade by following the directions at https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions.

**Comment by JeNeSuisPasDave** [comment]
That did workaround the cert export error. Here is the new debug log:

```
DPI scale: 1.25
startup, version: 3069 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/heind.CORP/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/heind.CORP/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/heind.CORP/AppData/Roaming/Sublime Text 3/Installed Packages
pre session restore time: 0.217317
warning: mnemonic E not found in menu caption Disable
warning: mnemonic S not found in menu caption Highlit style
startup time: 0.259317
first paint time: 0.262317
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin Emmet.emmet-plugin
reloading plugin Hipster Ipsum.hipsteripsum
reloading plugin InsertDate.insert_date
reloading plugin Keymaps.Keymaps
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.gather_missing_links
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.insert_references
reloading plugin MarkdownEditing.jumpToMarker
reloading plugin MarkdownEditing.list_markdown_references
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.paste_as_link
reloading plugin MarkdownEditing.paste_as_reference
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.underlined_headers
reloading plugin Origami.origami
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS.scss_completions
reloading plugin Select Quoted.select_quotes
reloading plugin WordCount.WordCount
reloading plugin Wrap Plus.wrap_plus
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
plugins loaded
InsertDate settings changed
reloading Packages/User/Package Control.sublime-settings
warning: mnemonic E not found in menu caption Disable
warning: mnemonic S not found in menu caption Highlit style
Emmet: No need to update PyV8
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3069
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Generating new CA bundle from system certificate store
Package Control: Exported certificate "Microsoft Root Certificate Authority"
Package Control: Skipping certificate "Thawte Timestamping CA" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Skipping certificate "Microsoft Root Authority" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Exported certificate "Microsoft Root Certificate Authority 2011"
Package Control: Skipping certificate "Microsoft Authenticode(tm) Root Authority" since it is no longer valid
Package Control: Error parsing filetime - high: "103822103", low: "133056512", epoch seconds: "32946780112.0"
Package Control: Exported certificate "HEIND201-HV.dev.aspentech.com"
Package Control: Exported certificate "Microsoft Root Certificate Authority 2010"
Package Control: Skipping certificate "Copyright (c) 1997 Microsoft Corp." since it is no longer valid
Package Control: Skipping certificate "NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc." since it is no longer valid
Package Control: Exported certificate "UTN-USERFirst-Object"
Package Control: Exported certificate "Thawte Premium Server CA"
Package Control: Exported certificate "GeoTrust Global CA"
Package Control: Exported certificate "Baltimore CyberTrust Root"
Package Control: Exported certificate "Equifax Secure Certificate Authority"
Package Control: Exported certificate "Entrust Root Certification Authority"
Package Control: Exported certificate "GlobalSign Root CA"
Package Control: Exported certificate "Starfield Class 2 Certification Authority"
Package Control: Exported certificate "DigiCert Global Root CA"
Package Control: Skipping certificate "GTE CyberTrust Global Root" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Exported certificate "thawte Primary Root CA"
Package Control: Skipping certificate "Class 3 Public Primary Certification Authority" since it uses the signature algorithm md2WithRSAEncryption
Package Control: Skipping certificate "VeriSign Commercial Software Publishers CA" since it is no longer valid
Package Control: Skipping certificate "Thawte Premium Server CA" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Exported certificate "DigiCert High Assurance EV Root CA"
Package Control: Exported certificate "Entrust.net Certification Authority (2048)"
Package Control: Skipping certificate "Class 3 Public Primary Certification Authority" since it is no longer valid
Package Control: Exported certificate "VeriSign Class 3 Public Primary Certification Authority - G5"
Package Control: Exported certificate "http://www.valicert.com/"
Package Control: Exported certificate "Go Daddy Class 2 Certification Authority"
Package Control: Skipping certificate "VeriSign Commercial Software Publishers CA" since it is no longer valid
Package Control: Exported certificate "DigiCert Assured ID Root CA"
Package Control: Exported certificate "AddTrust External CA Root"
Package Control: Exported certificate "dev-SHYE-W2K8R2-CA"
Package Control: Exported certificate "dev-ATA1-07-CA-UAT1"
Package Control: Exported certificate "dev-IMOSVMHOST-CA"
Package Control: Exported certificate "dev-LYNC-SOC-CA"
Package Control: Exported certificate "dev-ATA1-07-CA-UAT1"
Package Control: Exported certificate "dev-LYNC-SOC-CA"
Package Control: Exported certificate "dev-ATA1-07-CA"
Package Control: Exported certificate "MSIT Machine Auth CA 2"
Package Control: Exported certificate "COMODO Code Signing CA 2"
Package Control: Exported certificate "Microsoft Internet Authority"
Package Control: Exported certificate "Microsoft Secure Server CA 2011"
Package Control: Exported certificate "Microsoft IT SSL SHA1"
Package Control: Exported certificate "UTN-USERFirst-Hardware"
Package Control: Exported certificate "Microsoft Code Signing PCA"
Package Control: Skipping certificate "Root Agency" since it uses the signature algorithm md5WithRSAEncryption
Package Control: Exported certificate "www.verisign.com/CPS Incorp.by Ref. LIABILITY LTD.(c)97 VeriSign"
Package Control: Skipping certificate "Microsoft Windows Hardware Compatibility" since it is no longer valid
Package Control: Exported certificate "dev-SHYE-W2K8R2-CA"
Package Control: Exported certificate "dev-ATA1-07-CA-UAT1"
Package Control: Exported certificate "dev-IMOSVMHOST-CA"
Package Control: Exported certificate "dev-LYNC-SOC-CA"
Package Control: Exported certificate "dev-ATA1-07-CA-UAT1"
Package Control: Exported certificate "dev-LYNC-SOC-CA"
Package Control: Exported certificate "dev-ATA1-07-CA-UAT1"
Package Control: Exported certificate "dev-ATA1-07-CA"
Package Control: Exported certificate "dev-ATA1-07-CA-UAT1"
Package Control: Finished generating new CA bundle at C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.system-ca-bundle
Package Control: Created blank user CA bundle
Package Control: Regnerated the merged CA bundle from the system and user CA bundles
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading channel. URL error [WinError 10054] An existing connection was forcibly closed by the remote host downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-02-04 13:15:12, next run at 2015-02-04 14:15:12 or after
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3069
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. Connection refused (errno 12029) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading channel. URL error [WinError 10054] An existing connection was forcibly closed by the remote host downloading https://packagecontrol.io/channel_v3.json.
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3069
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at C:\Users\heind.CORP\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading channel. URL error [WinError 10054] An existing connection was forcibly closed by the remote host downloading https://packagecontrol.io/channel_v3.json.
error: Package Control

There are no packages ready for upgrade
```

**Comment by wbond** [comment]
Something on your machine or network is screwing up the connection.

Do you perhaps have a proxy on your network?

**Comment by JeNeSuisPasDave** [comment]
No proxy's, but this machine is behind a corporate firewall that blocks all kinds of things. FYI, the packagecontrol.io web site doesn't work from this machine either. The browser says the page failed due to a connection reset.

What's weird is that once in a while the packagecontrol.io web pages make it through just fine. Most times, however, they fail.

I'm not certain the firewall is intentionally blocking them. If it was intentional (i.e. blacklisted) then usually I will see a message like "we blocked this page because 'x'. If you think this is incorrect, contact your system administrator" from the firewall software.

It's almost like something is broken in the HTTP/HTTPS protocol. Perhaps there is something unusual in the protocol/handshaking that the firewall isn't understanding, so it drops the connection.

I did setup the Internet Connection settings to only have TLS 1.0, 1.1, 1.2. I also tried turning off SPDY. No joy.


I don't see this issue with every site (actually, I've only noticed it with packagecontrol.io).
I never have trouble accessing packagecontrol.io from my home systems.

**Comment by wbond** [comment]
Well, packagecontrol.io does not allow SSL v3 connection since that protocol is considered insecure due to https://www.openssl.org/~bodo/ssl-poodle.pdf. It only allows TLS 1.x. My guess is that it is related to that, especially if you can visit https://sublime.wbond.net and get redirected to packagecontrol.io. sublime.wbond.net still works with an old SHA1 certificate supporting SSLv3 because old versions of Package Control only support that.
