### ISSUE TITLE
Unable to install packages on Windows XP SP3

### ISSUE THREAD

**Issue by sroucheray** [wbond/package_control#865]
I'm opening this bug following the #826 close.

I have installed the last dev build 3068 (I am not sure about the 3.0.1 quoted by @wbond in the last comment of bug #826) and still have problem with packages I cannot install any of them. Here are the logs.

```
DPI scale: 1
startup, version: 3068 windows x32 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Documents and Settings/sroucheray.SUBSEND/Application Data/Sublime Text 3/Packages
state path: /C/Documents and Settings/sroucheray.SUBSEND/Application Data/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Documents and Settings/sroucheray.SUBSEND/Application Data/Sublime Text 3/Installed Packages
generating syntax summary
pre session restore time: 1.93713
startup time: 2.10913
first paint time: 2.12412
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 25 missing packages
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/colinta/SublimeChangeQuotes/zip/2.0.1.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "package_control.download_manager in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.wininet_downloader in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 377, in download
Package Control.package_control.downloaders.win_downloader_exception.WinDownloaderException: Error downloading package. Secure channel error, server not providing SSL (errno 12157) during HTTP write phase of downloading https://codeload.github.com/colinta/SublimeChangeQuotes/zip/2.0.1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 111, in run
  File "package_control.automatic_upgrader in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 155, in install_missing
  File "package_control.package_manager in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 756, in install_package
  File "package_control.download_manager in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 308, in fetch
  File "package_control.download_manager in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 264, in fetch
  File "package_control.downloaders.urllib_downloader in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 102, in download
  File "package_control.downloaders.urllib_downloader in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 275, in setup_opener
  File "package_control.ca_certs in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 50, in get_ca_bundle_path
  File "package_control.ca_certs in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 139, in get_system_ca_bundle_path
  File "package_control.ca_certs in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 394, in _win_create_ca_bundle
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 472, in parse
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 452, in load
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 452, in load
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 447, in load
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 95, in read
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 174, in _read_value
  File "package_control.http.x509 in C:\Documents and Settings\sroucheray.SUBSEND\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 245, in _decode_integer
TypeError: 'bytes' object does not support item assignment
```

**Comment by wbond** [comment]
I believe you are not running Package Control 3.0.1. You can follow the directions at https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions to make sure you are using the latest version.

Then make sure you follow the directions at https://github.com/wbond/package_control/blob/master/contributing.md to provide a full debug log.

**Comment by sroucheray** [comment]
Great that worked thanks for the really fast feedback :) 
And 3.0.1 is Package Control version, not SublimeText version. Sorry about that.
