### ISSUE TITLE
Can't install or upgrade packages

### ISSUE THREAD

**Issue by ncvc** [wbond/package_control#866]
On Ubuntu 14.10

I open the Command Pallete, go to Package Control: Install Package, and nothing happens (no text box for installing new packages, etc.). The same thing happens for Upgrade Package.

I have the following console output (from startup until error):

```
DPI scale: 1
startup, version: 3065 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/ncvc/.config/sublime-text-3/Packages
state path: /home/ncvc/.config/sublime-text-3/Local
hardware concurrency: 4
zip path: /opt/sublime_text/Packages
zip path: /home/ncvc/.config/sublime-text-3/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 9 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 196 cache hits: 194
pre session restore time: 0.127519
using gamma: 1 (err: 0)
startup time: 0.262224
first paint time: 0.294325
launching: /opt/sublime_text/plugin_host
loaded 893 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 001-bz2.inject
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0ssl-linux.inject
Linux SSL: enabling custom linux ssl module
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin Alignment.Alignment
reloading plugin FindKeyConflicts.find_key_conflicts
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin Pretty JSON.PrettyJson
[Errno 2] No such file or directory: 'jq'
reloading plugin Arduino-like IDE.StinoStarter
reloading plugin Python Flake8 Lint.Flake8Lint
generating syntax summary
found 9 files for base name Main.sublime-menu
reloading plugin Python Flake8 Lint.lint
reloading plugin Python Flake8 Lint.monkey_patching
reloading plugin SFTP.SFTP
SFTP: enabling custom linux ssl module
SFTP: successfully loaded _ssl module for libssl.so.1.0.0
plugins loaded
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/bootstrap.py", line 92, in plugin_loaded
    loader.add('00', 'package_control', base_loader_code)
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/package_control/loader.py", line 86, in add
    with zipfile.ZipFile(loader_package_path, mode) as z:
  File "./zipfile.py", line 919, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/ncvc/.config/Installed Packages/0_package_control_loader.sublime-package'
Package Control: Fetching list of available packages
  Platform: linux-x64
  Sublime Text Version: 3065
  Package Control Version: 2.0.1-beta3
Package Control: Download Debug
  URL: https://packagecontrol.io/channel.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found system CA bundle at /usr/lib/ssl/certs/ca-certificates.crt
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at /home/ncvc/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL
  Using TLSv1/SSLv3 with cipher ECDHE-RSA-RC4-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
    expire date: Oct 29 23:59:59 2015 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel.json HTTP/1.1
  User-Agent: Sublime Package Control v2.0.1-beta3
  Connection: Keep-Alive
  Accept-Encoding: bzip2,gzip,deflate
  Host: packagecontrol.io
  If-Modified-Since: Tue, 03 Feb 2015 20:40:14 GMT
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 200 OK
  Server: nginx
  Date: Tue, 03 Feb 2015 20:52:30 GMT
  Content-Type: application/json
  Last-Modified: Tue, 03 Feb 2015 20:50:14 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
  Content-Encoding: gzip
Package Control: Caching https://packagecontrol.io/channel.json in /home/ncvc/.config/sublime-text-3/Packages/User/Package Control.cache/a67878a45ebe1d30b0f6a9dc5fbedd5a
Package Control: Installing 1 missing dependencies
Package Control: Fetching list of available packages
  Platform: linux-x64
  Sublime Text Version: 3065
  Package Control Version: 2.0.1-beta3
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-02-03 15:42:58, next run at 2015-02-03 16:42:58 or after
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: Fetching list of available packages
  Platform: linux-x64
  Sublime Text Version: 3065
  Package Control Version: 2.0.1-beta3
Package Control: Looking for git at: "/home/ncvc/bin/git", "/usr/local/sbin/git", "/usr/local/bin/git", "/usr/sbin/git", "/usr/bin/git", "/sbin/git", "/bin/git", "/usr/games/git", "/usr/local/games/git", "/usr/lib/jvm/java-8-oracle/bin/git", "/usr/lib/jvm/java-8-oracle/db/bin/git", "/usr/lib/jvm/java-8-oracle/jre/bin/git", "/usr/local/git/bin/git", "/usr/local/bin/git"
Package Control: Found git at "/usr/bin/git"
Package Control: Trying to execute command /usr/bin/git symbolic-ref -q HEAD
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/package_control/commands/install_package_command.py", line 43, in run
    'reinstall', 'pull', 'none'])
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/package_control/package_installer.py", line 101, in make_package_list
    settings.get('cache_length'), settings.get('debug')
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/package_control/upgraders/git_upgrader.py", line 93, in incoming
    info = self.get_working_copy_info()
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/package_control/upgraders/git_upgrader.py", line 48, in get_working_copy_info
    res = self.execute([binary, 'symbolic-ref', '-q', 'HEAD'], self.working_copy)
  File "/home/ncvc/.config/sublime-text-3/Packages/Package Control/package_control/cmd.py", line 115, in execute
    startupinfo=startupinfo, cwd=cwd, creationflags=flags)
  File "./subprocess.py", line 761, in __init__
ValueError: creationflags is only supported on Windows platforms
```

**Comment by wbond** [comment]
You are on an old beta build. Follow the directions at https://packagecontrol.io/docs/troubleshooting#Purging_Old_Versions to install 3.0.1. Feel free to open a new issue if you run into trouble with 3.0.1.
