### ISSUE TITLE
unable to list packages using package control : install package

### ISSUE THREAD

**Issue by ayushlodhi001** [wbond/package_control#872]
when I use install package nothing happens and in console this error comes up. 

```
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading channel. The requested security package does not exist (errno -2146893051) during HTTP write phase of downloading https://packagecontrol.io/channel_v3.json.
Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\automatic_upgrader.py", line 111, in run
    self.install_missing()
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\automatic_upgrader.py", line 139, in install_missing
    if self.installer.manager.install_package(dependency, is_dependency=True):
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\package_manager.py", line 679, in install_package
    packages = self.list_available_packages(exclude_dependencies=exclude_dependencies)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\package_manager.py", line 343, in list_available_packages
    repositories = self.list_repositories()
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\package_manager.py", line 271, in list_repositories
    channel_repositories = provider.get_repositories()
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\providers\channel_provider.py", line 189, in get_repositories
    self.fetch()
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\providers\channel_provider.py", line 86, in fetch
    'Error downloading channel.')
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\download_manager.py", line 308, in fetch
    return self.fetch(url, error_message, prefer_cached)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\download_manager.py", line 264, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\downloaders\urllib_downloader.py", line 102, in download
    self.setup_opener(url, timeout)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\downloaders\urllib_downloader.py", line 275, in setup_opener
    bundle_path = get_ca_bundle_path(self.settings)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\ca_certs.py", line 50, in get_ca_bundle_path
    system_ca_bundle_path = get_system_ca_bundle_path(settings)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\ca_certs.py", line 139, in get_system_ca_bundle_path
    _win_create_ca_bundle(settings, ca_path)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\ca_certs.py", line 376, in _win_create_ca_bundle
    not_after  = convert_filetime_to_datetime(cert_info.NotAfter)
  File "C:\Users\ayush\AppData\Roaming\SUBLIM~1\Packages\Package Control\package_control\ca_certs.py", line 544, in convert_filetime_to_datetime
    return datetime.datetime.fromtimestamp(epoch_seconds)
ValueError: timestamp out of range for platform localtime()/gmtime() function
```

**Comment by wbond** [comment]
This was fixed by 26b13dc4b81c32bcb10a71d309d6a546eed11420 and is available by checking out the master branch, or waiting for the release of 3.0.2.
