### ISSUE TITLE
Install Package not working

### ISSUE THREAD

**Issue by xRedLeader** [wbond/package_control#881]
When i go to use "Package Control: Install Package"
Then i select the package, this is the error i get regardless of the package i select (output from startup to package install):

```
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/admin/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/admin/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/admin/AppData/Roaming/Sublime Text 3/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 198 cache hits: 196
pre session restore time: 0.295438
startup time: 0.373438
first paint time: 0.389438
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin ColorPicker.sublimecp
reloading plugin DocBlockr.__init__
reloading plugin DocBlockr.jsdocs
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-02-17 09:48:51, next run at 2015-02-17 10:48:51 or after
Traceback (most recent call last):
  File "package_control.package_installer in C:\Users\admin\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 169, in on_done
  File "package_control.package_disabler in C:\Users\admin\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 104, in disable_packages
  File "package_control.package_io in C:\Users\admin\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 31, in package_file_exists
  File "./ntpath.py", line 121, in join
  File "./ntpath.py", line 103, in isabs
TypeError: 'in <string>' requires string as left operand, not list
```

I'm not sure why it is not working now, as i was able to install some plugins just 20 minutes beforehand.

**Comment by wbond** [comment]
Can you turn on the debug flag please?

**Comment by xRedLeader** [comment]
The debug flag was on at that point. I went and removed all the settings. Left it with just the debug flag set to true, and then i was able to install packages. So, i am not sure if it was a theme, or another setting that was stopping packages. But it works now. Thanks, sorry for the waste of time.

**Comment by wbond** [comment]
Hmm, the `debug` flag should print all sorts of info, including the PC version, http headers, and more. But either way, glad it is working again!
