### ISSUE TITLE
bz2 dependancy issues on OsX Yosemite

### ISSUE THREAD

**Issue by baldec** [wbond/package_control#927]
New to sublime text and I am having some issues with package control. Other than packages missing which seems to be an issue that began just as I began looking in to this... Timing...

When installing package control I get a warning telling me that bz2 dependancy is missing.

And when I try to check that dependancy it fails to resolve the issue. 

I didn't find an issue of this so here goes. My first GitHub entry, ohh dear. 

Debug log found below. 

--- Beginning of Console Log --- 
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/baldec/Library/Application Support/Sublime Text 3/Packages
state path: /Users/baldec/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/baldec/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.206325
using gpu buffer for window
first paint time: 0.264856
startup time: 0.294393
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/baldec/Library/Application Support/Sublime Text 3/Packages/User/Package Control.system-ca-bundle
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at /Users/baldec/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Successfully upgraded connection to packagecontrol.io:443 with SSL
  Using TLSv1/SSLv3 with cipher DHE-RSA-AES256-SHA
  Server SSL certificate:
    subject: CN=codexns.io,O=Codex Non Sufficit LC,L=Newbury,S=Massachusetts,C=US,serialNumber=471714639,businessCategory=Private Organization,incorporationState=Massachusetts,incorporationCountry=US
    subject alt name: dev.codexns.io, rc.codexns.io, packagecontrol.io, wbond.net, codexns.io
    expire date: Oct 29 23:59:59 2015 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-Modified-Since: Fri, 10 Apr 2015 02:40:03 GMT
  Accept-Encoding: gzip,deflate
  Host: packagecontrol.io
  Connection: Keep-Alive
  User-Agent: Package Control v3.0.1
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Fri, 10 Apr 2015 06:07:19 GMT
  Last-Modified: Fri, 10 Apr 2015 02:40:03 GMT
  Connection: keep-alive
  ETag: "55273803-16f99a"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/baldec/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-04-10 07:43:20, next run at 2015-04-10 08:43:20 or after
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: The dependency bz2 is not currently installed; installing
Package Control: Fetching list of available packages
  Platform: osx-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: The dependency specified, bz2, is not available
Package Control: The dependency bz2 could not be installed or updated
Package Control: The dependency bz2 has successfully been installed or updated
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.satisfy_dependencies_command in /Users/baldec/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 43, in run
TypeError: show_error() takes 1 positional argument but 2 were given
--- End of Console Log ---

**Comment by baldec** [comment]
And all of a sudden my brain woke up a bit... This is of course linked to missing packages... bz2 is a package... There is an issue about missing packages... Synapses connecting... Closing issue... Can always re-open it if the Missing packages issue doesn't resolve it...

End of gibberish...
