### ISSUE TITLE
Installed incorrectly

### ISSUE THREAD

**Issue by YaoC** [wbond/package_control#949]
When I installed the package control the error is as follow:
```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/cyao/.config/sublime-text-3/Packages
state path: /home/cyao/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/cyao/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage", "Package Control"]
pre session restore time: 0.074046
startup time: 0.177758
first paint time: 0.185044
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
Package Control: Error finding main directory from loader
reloading plugin 0_package_control_loader.01-ssl-linux
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "01-ssl-linux in /home/cyao/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package", line 6, in <module>
ImportError: cannot import name sys_path
reloading plugin package_control.Package Control
error: Package Control

This package appears to be installed incorrectly.

It should be installed as "Package Control", but seems to be installed as "package_control".

To fix the issue, please:

1. Open the "Preferences" menu
2. Select "Browse Packages…"
3. Rename the folder "package_control" to "Package Control"
4. Restart Sublime Text
reloading plugin package_control.bootstrap
plugins loaded
```
But when I renamed the folder according to the tips ， the `Package Control` in the `Preferences` disappeared

**Comment by FichteFoll** [comment]
Remove "Package Control" from the `ignored_packages` setting in your user settings file, then it will work.

It's really awesome that Jon added this startup debug line.

**Comment by YaoC** [comment]
Thanks a lot  :)
