### ISSUE TITLE
Proxy Issue During Installation on Ubuntu Behind Corp Firewall

### ISSUE THREAD

**Issue by AdamYoungberg** [wbond/package_control#992]
I've read all I can find about proxy issues and haven't found anything that can address the following ... if I've missed it, please be kind and point me to what I failed to find through Google and search on this site.

I am behind a corporate proxy and have been able to install Package Control under Windows by following the "manual" instructions [here](https://packagecontrol.io/installation#st3).

However, now I am trying to replicate the same process in Ubuntu (15.04) on the same network.  I have the system-wide proxy set, which works well for most apps.  I've tried the script install (even adding the proxy object to the ProxyHandler portion - i.e

    import urllib.request,os,hashlib; h = '462d6673ebd5b9ca297474c166b2e10d' + 'fd945a23b1a0642535aa906951315f52'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler({"http":"http://<username>:<password>@<proxy>:<port>"})) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)

I have also tried the manual method that worked in Windows.  However, using either method, I get very similar (identical?) behavior.  The Package Control.sublime-package file shows briefly in the Installed Packages directory, the "0_package_control_loader.sublime-package" file is created, and then the original file is deleted.  After restarting Sublime Text 3, Package Control is not installed.  The "0_package_control_loader.sublime-package" remains in the Installed Packages directory.

When I review the console during the install attempt I get this (this is the log using the manual method):

    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading Packages/Package Control/Package Control.sublime-settings
    Package Control: Downloading bootstrapped dependency ssl-linux
    reloading plugin 0_package_control_loader.00-package_control
    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "./threading.py", line 858, in run
      File "package_control.bootstrap in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 97, in bootstrap_dependency
      File "package_control.download_manager in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 340, in fetch
      File "package_control.downloaders.urllib_downloader in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 123, in download
      File "./urllib/request.py", line 475, in open
      File "./urllib/request.py", line 587, in http_response
      File "./urllib/request.py", line 507, in error
      File "./urllib/request.py", line 447, in _call_chain
      File "./urllib/request.py", line 1157, in http_error_407
      File "./urllib/request.py", line 1031, in http_error_auth_reqed
    ValueError: AbstractDigestAuthHandler does not support the following scheme: 'NEGOTIATE'

    Package Control: Settings change detected, clearing cache
    ignored packages updated to: ["Package Control", "Vintage"]
    unloading plugin Package Control.1_reloader
    unloading plugin Package Control.2_bootstrap
    unloading plugin Package Control.Package Control
    reloading Packages/Package Control/Package Control.sublime-settings
    Package Control: Settings change detected, clearing cache
    Package Control: Installing 2 missing dependencies
    Exception in thread Thread-20:
    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "package_control.automatic_upgrader in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 113, in run
      File "package_control.automatic_upgrader in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 145, in install_missing
      File "package_control.package_manager in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 864, in install_package
      File "package_control.package_manager in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 453, in list_available_packages
      File "package_control.package_manager in /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 347, in list_repositories
    TypeError: 'NoneType' object is not subscriptable

    reloading Packages/User/Preferences.sublime-settings
    Package Control: Removed orphaned package Package Control
    ignored packages updated to: ["Vintage"]
    error loading /home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package: [Errno 2] No such file or directory: '/home/<user>/.config/sublime-text-3/Installed Packages/Package Control.sublime-package'
    reloading Packages/User/Preferences.sublime-settings

I presume when reviewing the above that this is still a proxy authentication problem, since I see the "http_error_auth_reqed" message in the first traceback.  The problem is, since this is during the install, I don't know where to specify credentials.  I found [this](https://packagecontrol.io/docs/settings), which describes how to set the proxy in the settings file after Package Control is successfully installed, but I don't see anything for how to do this during the installation process.

Please help.

**Comment by wbond** [comment]
I believe this is solved by version 3.1.2, which will be installed if you follow the directions at https://packagecontrol.io/installation.

**Comment by AdamYoungberg** [comment]
Indeed you are right.  I apologize for not seeing such a simple solution.  Thanks for the quick turnaround.

**Comment by wbond** [comment]
Sorry if I mislead you. I did have to fix the bug and release 3.1.2 to solve your issue. I was just explaining that since the release you could grab it by visiting the installation page. :-)
