### ISSUE TITLE
Exception when installing inside console

### ISSUE THREAD

**Issue by Grokzen** [wbond/package_control#998]
This is the output from when i installed the extension inside the console.

```
>>> import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
186789
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading Packages/Package Control/Package Control.sublime-settings
Package Control: Downloading bootstrapped dependency ssl-linux
reloading plugin 0_package_control_loader.00-package_control
Package Control: Successfully downloaded bootstraped dependency ssl-linux
Exception in thread Thread-944:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "package_control.bootstrap in /home/grok/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 193, in bootstrap_dependency
  File "package_control.loader in /home/grok/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 207, in add
  File "/home/grok/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package/01-ssl-linux.py", line 8, in <module>
zipimport.ZipImportError: bad local file header in /home/grok/.config/sublime-text-3/Installed Packages/Package Control.sublime-package

Package Control: Settings change detected, clearing cache
```

Packages can not be installed after this. It can query all the packages from the server but gets this exception when tried to install

```
Traceback (most recent call last):
  File "package_control.package_installer in /home/grok/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in /home/grok/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 74, in disable_packages
zipimport.ZipImportError: bad local file header in /home/grok/.config/sublime-text-3/Installed Packages/Package Control.sublime-package
```

Using sublime text 3 Build: 3095

**Comment by wbond** [comment]
Did you already have Package Control installed, or was this a fresh install?

Also, did the issue go away after restarting Sublime Text?

**Comment by Grokzen** [comment]
I had it installed, it was buggy because none of the commands was loaded into the command pallet. So i removed all traces of the package and then i installed it again from the console.

After restarting st3 i do not see the error any longer when trying to install a package.
